---
format:
  html:
    toc: false
    embed-resources: true
---

{{< include problem_statement.qmd >}}

---

**Returned Response**: $Y_{D/A}$ and $f_A$

**Missing Values Argument**: $T_0$

**Adjusted Values Argument**: None.

**Solver Guesses Argument**: None.

**Given and Known Constants**: $P_{A,0}=1\text{ atm}$, $P_{B,0}=2\text{ atm}$, , $V= 2\text{ L}$, $A= 600\text{ cm}^2$, $U= 0.6 \text{ cal cm}^{-2} \text{ min}^{-1}\text{ K}^{-1}$, $T_{ex} =30\text{ °C}$, $t_f$ = 12 min, $k_{0,1} =  3.34 \times 10^9 \text{ mol cm}^{-3}\text{ min}^{-1}\text{ atm}^{-2}$, $k_{0,2} = 4.99 \times 10^9 \text{ mol cm}^{-3}\text{ min}^{-1}\text{ atm}^{-2}$, $E_1= 20.5\text{ kcal mol}^{-1}$, $E_2= 21.8\text{ kcal mol}^{-1}$, $\Delta H_1= -6,300 \text{ cal mol}^{-1}$, $\Delta H_2= -6,900 \text{ cal mol}^{-1}$, $\hat C_{p,A}= 7.4 \text{ cal mol}^{-1}\text{ K}^{-1}$, $\hat C_{p,B}= 8.6 \text{ cal mol}^{-1}\text{ K}^{-1}$, $\hat C_{p,D}= 10.7 \text{ cal mol}^{-1}\text{ K}^{-1}$, $\hat C_{p,Z}= 5.2 \text{ cal mol}^{-1}\text{ K}^{-1}$ and $\hat C_{p,U}= 10.3 \text{ cal mol}^{-1}\text{ K}^{-1}$.

**Calculated Fixed Input**:

$$
n_{A,0} = \frac{P_{A,0}V}{RT_0} \tag{5}
$$

$$
n_{B,0} = \frac{P_{B,0}V}{RT_0} \tag{6}
$$

$$
n_{D,0} = 0 \tag{7}
$$

$$
n_{Z,0} = 0 \tag{8}
$$

$$
n_{U,0} = 0 \tag{9}
$$

$$
P_0= P_{A,0} + P_{B,0} \tag{10}
$$

**Reactor Design and Ancillary Equations**:

$$
\frac{dn_A}{dt} = -Vr_1 \tag{11}
$$

$$
\frac{dn_B}{dt} = -V\left(r_1 + r_2\right) \tag{12}
$$

$$
\frac{dn_D}{dt} = V\left(r_1 - r_2\right) \tag{13}
$$

$$
\frac{dn_Z}{dt} = V\left(r_1 + r_2\right) \tag{14}
$$

$$
\frac{dn_U}{dt} = Vr_2 \tag{15}
$$

$$
\begin{align}
&\frac{dT}{dt} \left(n_A \hat C_{p,A} + n_B \hat C_{p,B} +n_D \hat C_{p,D} +n_Z \hat C_{p,Z} +n_U \hat C_{p,U} \right) - V \frac{dP}{dt} \\&= UA\left(T_e-T\right) - V\left(r_1 \Delta H_1 + r_2 \Delta H_2\right)
\end{align} \tag{16}
$$

$$
V\frac{dP}{dt} - R\left(n_A + n_B + n_D + n_Z + n_U \right)\frac{dT}{dt}=0 \tag{17}
$$

$$
P_A = \frac{n_ART}{V} \tag{18}
$$

$$
P_B = \frac{n_BRT}{V} \tag{19}
$$

$$
P_D = \frac{n_DRT}{V} \tag{20}
$$

**Reactor Model Solver**:

The reactor design equations are a set of 7 coupled IVODEs, equations (11) through (17). They can be solved numerically to find the values of $n_A$, $n_B$, $n_D$, $n_Z$, $n_U$, $T$, and $P$ as functions of $t$ in the range from $t=0$ to $t=t_f$.

The initial values are $t=0$, $n_A = n_{A,0}$, $n_B = n_{B,0}$, $n_D = n_{D,0}$, $n_Z = n_{Z,0}$, $n_U = n_{U,0}$, $T = T_0$, and $P=P_0$.

The stopping criterion is $t=t_f$.

**Response Calculation**:

$$
Y_{D/A}=\frac{n_D\Big\vert_{t=t_f}}{n_{A,0}} \tag{21}
$$

$$
f_A=\frac{n_{A,0} - n_A\Big\vert_{t=t_f}}{n_{A,0}} \tag{22}
$$
