rule reb_K_3_1:
    input:
        "reb_K_3_1/matlab/results/reb_K_3_1_results.csv",
        "reb_K_3_1/python/results/reb_K_3_1_results.csv"

rule reb_K_3_1_python:
    input:
        "reb_K_3_1/python/code/reb_K_3_1_calculations.py"
    output:
        "reb_K_3_1/python/results/reb_K_3_1_results.csv"
    shell:
        """
        python reb_K_3_1/python/code/reb_K_3_1_calculations.py
        """

rule reb_K_3_1_matlab:
    input:
        "reb_K_3_1/matlab/code/reb_K_3_1_calculations.m"
    output:
        "reb_K_3_1/matlab/results/reb_K_3_1_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_K_3_1/matlab/code');\
        reb_K_3_1_calculations;exit"
        """