---
format:
  html:
    toc: false
    embed-resources: true
---

{{< include problem_statement.qmd >}}

**Given**

$k_1$ = 3.37 lbmol h^-1^ ft^-3^ atm^-0.55^, $K_1$ = 12.0, $y_{H_2O,0}$ = 0.75, $y_{CO,0}$ = 0.24, $y_{CO_2,0}$ = 0.01, $P$ = 10 atm, $T$ = 675 K, $f_{CO,eq}$ = 0.96.

**Basis**

$V$ = 1 L.

**Necessary Equations**

$$
n_{CO,0} = \frac{y_{CO,0} PV}{RT} \tag{4}
$$

$$
n_{H_2O,0} = \frac{y_{H_2O,0} PV}{RT} \tag{5}
$$

$$
n_{CO_2,0} = \frac{y_{CO_2,0} PV}{RT} \tag{6}
$$

$$
n_{H_2,0} = 0 \tag{7}
$$

$$
n_{CO} = n_{CO,0}\left(1 - f_{CO}\right) \tag{8}
$$

$$
n_{CO} = n_{CO,0} - \xi_1 \quad \Rightarrow \quad \xi_1 = n_{CO,0} - n_{CO} \tag{9}
$$

$$
n_{H_2O} = n_{H_2O,0} - \xi_1 \tag{10}
$$

$$
n_{CO_2} = n_{CO_2,0} - \xi_1 \tag{11}
$$

$$
n_{H_2} = n_{H_2,0} + \xi_1 \tag{12}
$$

$$
P_{CO} = \frac{n_{CO}RT}{V} \tag{13}
$$

$$
P_{H_2O} = \frac{n_{H_2O}RT}{V} \tag{14}
$$

$$
P_{CO_2} = \frac{n_{CO_2}RT}{V} \tag{15}
$$

$$
P_{H_2} = \frac{n_{H_2}RT}{V} \tag{16}
$$

**Calculations**

1. Substitute the given values and the chosen basis into all equations.
2. Calculate the initial moles of CO, H~2~O, CO~2~, and H~2~ using equations (4) through (7).
3. Choose a CO conversion between 0 and 100%.
    a. Calculate the final moles of CO at that conversion using equation (8).
    b. Calculate the apparent extent of reaction using equation (9).
    c. Calculate the final moles of H~2~O, CO~2~, and H~2~ using equations (10) through (12).
    d. Calculate the final partial pressures of CO, H~2~O, CO~2~, and H~2~ using equations (13) through (16).
    e. Calculate the rate predicted by equation (2).
    f. Calculate the rate predicted by equation (3).
4. Repeat step 3 to generate a set of conversions that span the range from 0 to 100% and the corresponding rates predicted by equations (2) and (3).
5. Plot the full set of results.
6. Plot the results for conversions between 85% and 100%.
