---
format:
  html:
    toc: false
    embed-resources: true
---

{{< include problem_statement.qmd >}}

**Reactor Design Equations**

Steady-state mole balances on A, B, and Z are shown in equations (3), (4), and (5).

$$
0 = \dot n_{A,in} - \dot n_A - r_1 V \tag{3}
$$

$$
0 = \dot n_{B,in} - \dot n_B - r_1 V \tag{4}
$$

$$
0 = - \dot n_Z + r_1 V \tag{5}
$$

Start with eq-cstr_mol_balance
$$
\frac{V}{\dot V}\frac{d \dot n_i}{dt} + \frac{\dot n_i}{\dot V}\frac{dV}{dt} - \frac{\dot n_iV}{\dot V^2}\frac{d \dot V}{dt} = \dot n_{i,in} - \dot n_i + V \sum_j \nu_{i,j}r_j
$$

An energy balance on the reacting fluid takes the form shown in equation (6).

$$
0 = \dot Q - \rho \dot V_{in} \tilde C_p  \left( T - T_{in} \right) - r_1 V \Delta H_1 \tag{6}
$$

Start with eq-cstr_energy_balance
$$
\begin{split}
\frac{V}{\dot V}\sum_i \left( \dot n_i \hat C_{p,i}  \right) &\frac{dT}{dt} - V \frac{dP}{dt} - P\frac{dV}{dt} = \dot Q - \dot W \\&- \sum_i\dot n_{i,in} \int_{T_{in}}^T \hat C_{p,i}dT - V\sum_j r_j \Delta H_j
\end{split}
$$

The design equations form a set of four ATEs that can be solved to find the values of $\dot n_A$, $\dot n_B$, $\dot n_Z$, and $T$.

**Ancillary Equations for Solving the Design Equations**

The following quantities are known and constant: $\Delta H_1^0$, $\tilde C_p$, $\rho$, $k_{0,1}$, $E_1$, $K_{0,1}$, $C_{A,in}$, $C_{B,in}$, $\dot V_{in}$, $T_{in}$, $V$, $P$, $T_{ex}$, $V_{ex}$, $A$, and $U$.

The inlet molar flow rates of A and B in equations (3) and (4) can be calculated using the defining equation for concentration, equations (7) and (8).

$$
\dot n_{A,in} = \dot V_{in}C_{A,in} \tag{7}
$$

$$
\dot n_{B,in} = \dot V_{in}C_{B,in} \tag{8}
$$

The rate of reaction (1) can be calculated using the rate expression, equation (2). The rate coefficient in equation (2) can be calculated using the Arrhenius expression, equation (9). The concentrations appearing in equation (2) can be calculated using equations (10) through (12). Assuming the liquid to be an incompressible ideal mixture, the outlet volumetric flow rate in equations (10) through (12) will equal the inlet volumetric flow rate, equation (13). The equilibrium constant in equation (2) can be calculated using equation (14).

$$
k_1 = k_{0,1} \exp{\left(  \frac{-E_1}{RT} \right)} \tag{9}
$$

$$
C_A = \frac{\dot n_A}{\dot V} \tag{10}
$$

$$
C_B = \frac{\dot n_B}{\dot V} \tag{11}
$$

$$
C_Z = \frac{\dot n_Z}{\dot V} \tag{12}
$$

$$
\dot V = \dot V_{in} \tag{13}
$$

$$
K_1 = K_{0,1}\exp{\frac{-\Delta H_1^0}{RT}} \tag{14}
$$

The rate of heat transfer from the exchange fluid to the reacting fluid can be calculated using equation (15).

$$
\dot Q = UA \left( T_{ex} - T \right) \tag{15}
$$

**Solution of the Design Equations**

**Ancillary Equations for Calculating the Remaining Unknown Outlet Values**
