rule reb_15_4_1:
    input:
        "reb_15_4_1/python/results.csv",
        "reb_15_4_1/matlab/results.csv",
        "../RE_Basics/examples/reb_15_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_15_4_1/equations.qmd",
        "../RE_Basics/examples/reb_15_4_1/network_schematic.png",
        "../RE_Basics/examples/reb_15_4_1/results.csv",
        "../SCoRE/reb_examples/reb_15_4_1/reb_15_4_1.py",
        "../SCoRE/reb_examples/reb_15_4_1/reb_15_4_1.m"

rule reb_15_4_1_python:
    input:
        "reb_15_4_1/python/reb_15_4_1.py"
    output:
        "reb_15_4_1/python/results.csv"
    shell:
        """
        python3 reb_15_4_1/python/reb_15_4_1.py
        """

rule reb_15_4_1_matlab:
    input:
        "reb_15_4_1/matlab/reb_15_4_1.m"
    output:
        "reb_15_4_1/matlab/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_15_4_1/matlab');reb_15_4_1;exit"
        """

rule reb_15_4_1_re_basics:
    input:
        "reb_15_4_1/narrative.qmd",
        "reb_15_4_1/equations.qmd",
        "reb_15_4_1/network_schematic.png",
        "reb_15_4_1/python/results.csv"
    output:
        "../RE_Basics/examples/reb_15_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_15_4_1/equations.qmd",
        "../RE_Basics/examples/reb_15_4_1/network_schematic.png",
        "../RE_Basics/examples/reb_15_4_1/results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_15_4_1
        mkdir ../RE_Basics/examples/reb_15_4_1
        cp reb_15_4_1/narrative.qmd ../RE_Basics/examples/reb_15_4_1
        cp reb_15_4_1/equations.qmd ../RE_Basics/examples/reb_15_4_1
        cp reb_15_4_1/network_schematic.png ../RE_Basics/examples/reb_15_4_1
        cp reb_15_4_1/python/results.csv ../RE_Basics/examples/reb_15_4_1
        """

rule reb_15_4_1_score:
    input:
        "reb_15_4_1/python/reb_15_4_1.py",
        "reb_15_4_1/matlab/reb_15_4_1.m"
    output:
        "../SCoRE/reb_examples/reb_15_4_1/reb_15_4_1.py",
        "../SCoRE/reb_examples/reb_15_4_1/reb_15_4_1.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_15_4_1
        mkdir ../SCoRE/reb_examples/reb_15_4_1
        cp reb_15_4_1/python/reb_15_4_1.py ../SCoRE/reb_examples/reb_15_4_1
        cp reb_15_4_1/matlab/reb_15_4_1.m ../SCoRE/reb_examples/reb_15_4_1
        """
