rule reb_19_1:
    input:
        "reb_19_1/Data/reb_19_1_data.csv",
        "reb_19_1/Data/reb_19_1_data_65.csv",
        "reb_19_1/Data/reb_19_1_data_73.csv",
        "reb_19_1/Data/reb_19_1_data_82.csv",
        "reb_19_1/Data/reb_19_1_data_90.csv",
        "reb_19_1/Data/reb_19_1_data_filenames.csv",
        "../RE_Basics/Data/reb_19_1_data.csv",
        "reb_19_1/Results/reb_19_1_Arrhenius_diff.csv",
        "reb_19_1/Results/reb_19_1_Arrhenius_resp_fcn.csv",
        "reb_19_1/Results/reb_19_1_diff_params.csv",
        "reb_19_1/Results/reb_19_1_resp_fcn_params.csv",
        "reb_19_1/Results/reb_19_1_Arrhenius_diff.png",
        "reb_19_1/Results/reb_19_1_Arrhenius_resp_fcn.png",
        "reb_19_1/Results/reb_19_1_model_65.png",
        "reb_19_1/Results/reb_19_1_model_73.png",
        "reb_19_1/Results/reb_19_1_model_82.png",
        "reb_19_1/Results/reb_19_1_model_90.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_90.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_90.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_90.png",
        "../RE_Basics/Graphics/reb_19_1_Arrhenius_diff.png",
        "../RE_Basics/Graphics/reb_19_1_Arrhenius_resp_fcn.png",
        "../RE_Basics/Graphics/reb_19_1_model_65.png",
        "../RE_Basics/Graphics/reb_19_1_model_73.png",
        "../RE_Basics/Graphics/reb_19_1_model_82.png",
        "../RE_Basics/Graphics/reb_19_1_model_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_90.png"

rule reb_19_1_data:
    input: "reb_19_1/Code/reb_19_1_data_generator.py"
    output:
        "reb_19_1/Data/reb_19_1_data.csv",
        "../RE_Basics/Data/reb_19_1_data.csv"
    shell:
        """
        python reb_19_1/Code/reb_19_1_data_generator.py
        """

rule reb_19_1_data_blocks:
    input: 
        "reb_19_1/Code/reb_19_1_create_data_blocks.py",
        "reb_19_1/Data/reb_19_1_data.csv"
    output:
        "reb_19_1/Data/reb_19_1_data_65.csv",
        "reb_19_1/Data/reb_19_1_data_73.csv",
        "reb_19_1/Data/reb_19_1_data_82.csv",
        "reb_19_1/Data/reb_19_1_data_90.csv",
        "reb_19_1/Data/reb_19_1_data_filenames.csv"
    shell:
        """
        python reb_19_1/Code/reb_19_1_create_data_blocks.py
        """

rule reb_19_1_results_resp:
    input:
        "reb_19_1/Code/reb_19_1_calcs_response_fcn.py",
        "reb_19_1/Code/reb_19_1_response_function.py",
        "reb_19_1/Data/reb_19_1_data_65.csv",
        "reb_19_1/Data/reb_19_1_data_73.csv",
        "reb_19_1/Data/reb_19_1_data_82.csv",
        "reb_19_1/Data/reb_19_1_data_90.csv",
        "reb_19_1/Data/reb_19_1_data_filenames.csv"
    output:
        "reb_19_1/Results/reb_19_1_resp_fcn_params.csv",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_65.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_73.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_82.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_parity_90.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_CA0_90.png",
        "reb_19_1/Results/reb_19_1_resp_fcn_residual_t_rxn_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_65.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_73.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_82.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_parity_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_CA0_90.png",
        "../RE_Basics/Graphics/reb_19_1_resp_fcn_residual_t_rxn_90.png"
    shell:
        """
        python reb_19_1/Code/reb_19_1_calcs_response_fcn.py
        """

rule reb_19_1_diff:
    input:
        "reb_19_1/Code/reb_19_1_calcs_diff_analysis.py",
        "reb_19_1/Data/reb_19_1_data_65.csv",
        "reb_19_1/Data/reb_19_1_data_73.csv",
        "reb_19_1/Data/reb_19_1_data_82.csv",
        "reb_19_1/Data/reb_19_1_data_90.csv",
        "reb_19_1/Data/reb_19_1_data_filenames.csv"
    output:
        "reb_19_1/Results/reb_19_1_diff_params.csv",
        "reb_19_1/Results/reb_19_1_model_65.png",
        "reb_19_1/Results/reb_19_1_model_73.png",
        "reb_19_1/Results/reb_19_1_model_82.png",
        "reb_19_1/Results/reb_19_1_model_90.png",
        "../RE_Basics/Graphics/reb_19_1_model_65.png",
        "../RE_Basics/Graphics/reb_19_1_model_73.png",
        "../RE_Basics/Graphics/reb_19_1_model_82.png",
        "../RE_Basics/Graphics/reb_19_1_model_90.png"
    shell:
        """
        python reb_19_1/Code/reb_19_1_calcs_diff_analysis.py
        """

rule reb_19_1_Arrhenius_resp:
    input:
        "reb_19_1/Code/reb_19_1_Arrhenius_resp_fcn.py",
        "reb_19_1/Results/reb_19_1_resp_fcn_params.csv"
    output:
        "reb_19_1/Results/reb_19_1_Arrhenius_resp_fcn.csv",
        "reb_19_1/Results/reb_19_1_Arrhenius_resp_fcn.png",
        "../RE_Basics/Graphics/reb_19_1_Arrhenius_resp_fcn.png"
    shell:
        """
        python reb_19_1/Code/reb_19_1_Arrhenius_resp_fcn.py
        """

rule reb_19_1_Arrhenius_diff:
    input:
        "reb_19_1/Code/reb_19_1_Arrhenius_diff.py",
        "reb_19_1/Results/reb_19_1_diff_params.csv"
    output:
        "reb_19_1/Results/reb_19_1_Arrhenius_diff.csv",
        "reb_19_1/Results/reb_19_1_Arrhenius_diff.png",
        "../RE_Basics/Graphics/reb_19_1_Arrhenius_diff.png"
    shell:
        """
        python reb_19_1/Code/reb_19_1_Arrhenius_diff.py
        """