rule reb_23_3_2:
    input:
        "../RE_Basics/examples/reb_23_3_2/narrative.qmd",
        "../RE_Basics/examples/reb_23_3_2/equations.qmd"

rule reb_23_3_2_data:
    input:
        
    output:
        
    shell:
        """
        
        """

rule reb_23_3_2_python:
    input:
        
    output:
        
    shell:
        """
        
        """

rule reb_23_3_2_matlab:
    input:
        
    output:
        
    shell:
        """
        matlab -nodisplay -r "cd('reb_23_3_2/matlab');reb_23_3_2;exit"
        """

rule reb_23_3_2_re_basics:
    input:
        "reb_23_3_2/narrative.qmd",
        "reb_23_3_2/equations.qmd"
    output:
        "../RE_Basics/examples/reb_23_3_2/narrative.qmd",
        "../RE_Basics/examples/reb_23_3_2/equations.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_23_3_2
        mkdir ../RE_Basics/examples/reb_23_3_2
        cp reb_23_3_2/narrative.qmd ../RE_Basics/examples/reb_23_3_2
        cp reb_23_3_2/equations.qmd ../RE_Basics/examples/reb_23_3_2
        """

rule reb_23_3_2_score:
    input:
        
    output:
        
    shell:
        """
        
        """