include: "reb_3_1/Snakefile"
include: "reb_3_2/Snakefile"
include: "reb_3_3/Snakefile"
include: "reb_3_4/Snakefile"
include: "reb_4_1/Snakefile"
include: "reb_4_2/Snakefile"
include: "reb_4_3/Snakefile"
include: "reb_4_4/Snakefile"
include: "reb_9_6_1/Snakefile"
include: "reb_9_6_2/Snakefile"
include: "reb_9_6_3/Snakefile"
include: "reb_9_6_4/Snakefile"
include: "reb_10_5_1/Snakefile"
include: "reb_10_5_2/Snakefile"
include: "reb_10_5_3/Snakefile"
include: "reb_12_7_1/Snakefile"
include: "reb_12_7_2/Snakefile"
include: "reb_12_7_3/Snakefile"
include: "reb_12_7_4/Snakefile"
include: "reb_12_7_5/Snakefile"
include: "reb_12_7_6/Snakefile"
include: "reb_13_7_1/Snakefile"
include: "reb_13_7_2/Snakefile"
include: "reb_13_7_3/Snakefile"
include: "reb_13_7_4/Snakefile"
include: "reb_13_7_5/Snakefile"
include: "reb_13_7_6/Snakefile"
include: "reb_15_4_1/Snakefile"
include: "reb_19_1/Snakefile"
include: "reb_19_2/Snakefile"
include: "reb_19_3/Snakefile"
include: "reb_19_4/Snakefile"
include: "reb_20_1/Snakefile"
include: "reb_20_2/Snakefile"
include: "reb_20_3/Snakefile"
include: "reb_21_1/Snakefile"
include: "reb_21_2/Snakefile"
include: "reb_21_3/Snakefile"
include: "reb_I_6/Snakefile"
include: "reb_J_6_1/Snakefile"
include: "reb_J_6_2/Snakefile"
include: "reb_J_6_3/Snakefile"
include: "reb_K_4_1/Snakefile"

# Specify that function  as the input for the all rule
rule all:
    input:

