rule reb_10_3:
    input:
        "reb_10_3/Results/reb_10_3_results.csv",
        "reb_10_3/Results/reb_10_3_two_par_results.csv",
        "reb_10_3/Results/reb_10_3_parity.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yAin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yBin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yYin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yZin.png",
        "reb_10_3/Results/reb_10_3_2_par_parity.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yAin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yBin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yYin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yZin.png",
        "../RE_Basics/Graphics/reb_10_3_parity.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yAin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yBin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yYin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yZin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_parity.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yAin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yBin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yYin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yZin.png"

rule reb_10_3_results:
    input:
        "reb_10_3/Code/reb_10_3_calculations.py",
        "reb_10_3/Code/response_function.py",
        "reb_10_2/Data/reb_10_2_data.csv"
    output:
        "reb_10_3/Results/reb_10_3_results.csv",
        "reb_10_3/Results/reb_10_3_parity.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yAin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yBin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yYin.png",
        "reb_10_3/Results/reb_10_3_residuals_vs_yZin.png",
        "../RE_Basics/Graphics/reb_10_3_parity.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yAin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yBin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yYin.png",
        "../RE_Basics/Graphics/reb_10_3_residuals_vs_yZin.png"
    shell:
        """
        python3 reb_10_3/Code/reb_10_3_calculations.py
        """

rule reb_10_3_2_par_results:
    input:
        "reb_10_3/Code/reb_10_3_two_par_calculations.py",
        "reb_10_3/Code/two_par_response_function.py",
        "reb_10_2/Data/reb_10_2_data.csv"
    output:
        "reb_10_3/Results/reb_10_3_two_par_results.csv",
        "reb_10_3/Results/reb_10_3_2_par_parity.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yAin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yBin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yYin.png",
        "reb_10_3/Results/reb_10_3_2_par_residuals_vs_yZin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_parity.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yAin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yBin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yYin.png",
        "../RE_Basics/Graphics/reb_10_3_2_par_residuals_vs_yZin.png"
    shell:
        """
        python3 reb_10_3/Code/reb_10_3_two_par_calculations.py
        """