rule reb_K_3_2:
    input:
        "reb_K_3_2/matlab/results/reb_K_3_2_results.csv",
        "reb_K_3_2/python/results/reb_K_3_2_results.csv"

rule reb_K_3_2_python:
    input:
        "reb_K_3_2/python/code/reb_K_3_2_calculations.py"
    output:
        "reb_K_3_2/python/results/reb_K_3_2_results.csv"
    shell:
        """
        python reb_K_3_2/python/code/reb_K_3_2_calculations.py
        """

rule reb_K_3_2_matlab:
    input:
        "reb_K_3_2/matlab/code/reb_K_3_2_calculations.m"
    output:
        "reb_K_3_2/matlab/results/reb_K_3_2_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_K_3_2/matlab/code');\
        reb_K_3_2_calculations;exit"
        """