---
format:
  html:
    toc: false
    embed-resources: true
---

{{< include problem_statement.qmd >}}

**Reactor Design Equations**

Equations (3) and (4) are a mole balances on reagents A and B, respectively.

$$
\frac{dn_A}{dt} = - r_1 V \tag{3}
$$

$$
\frac{dn_B}{dt} =  r_1 V \tag{4}
$$

An energy balance on the reacting fluid is presented in equation (5).

$$
\left( n_A \hat C_{p,A} + n_B \hat C_{p,B} \right) \frac{dT}{dt} - V\frac{dP}{dt} = - V r_1 \Delta H_1 \tag{5}
$$

Taking the time derivative of the ideal gas law and noting the $V$ is constant yields equation (6).

$$
-RT \frac{dn_A}{dt} - RT \frac{dn_B}{dt} - \left( n_A + n_B \right)R \frac{dT}{dt} + V \frac{dP}{dt} = 0 \tag{6}
$$

**Ancillary Equations for Solving the Design Equations**

The following constant values are known: the pre-exponential factor, $k_{0,1}$, the activation energy, $E_1$, the heat of reaction, $\Delta H^0_1$, the molar heat capacity of A, $\hat C_{p,A}$, the molar heat capacity of B, $\hat C_{p,B}$, the reactor volume, $V$, the initial temperature, $T_0$, the initial pressure, $P_0$, and the final temperature, $T_f$.

The rate, $r_1$, appearing in equations (3), (4), and (5) can be calculated using equation (2). The rate coefficient, $k_1$ in equation (2) can be calculated using the Arrhenius expression, equation (7), and the concentration of A, $C_A$, in equation (2) can be calculated using the defining equation for concentration,equation (8).

$$
k_1 = k_{0,1} \exp{\left( \frac{-E_1}{RT} \right)} \tag{7}
$$

$$
C_A = \frac{n_A}{V} \tag{8}
$$

**Solution of the Design Equations**

$$
n_{A,0} = \frac{P_0V}{RT_0} \tag{9}
$$

| Variable | Initial Value | Stopping Criterion |
|:-------|:-------:|:-------:|
| $t$ | $0$ |  |
| $n_A$ | $n_{A,0}$ |
| $n_B$ | $0$ | |
| $T$ | $T_0$ | $T_f$ |
| $P$ | $P_0$ |  |

: Initial values and stopping criterion for solving the design equations. {tbl-colwidths="[20, 40, 40]"}

**Ancillary Equations for Calculating the Remaining Unknown Outlet Values**

Solving the design equations gives all of the outputs.







**Stuff that might be useful in callouts**

Start with eq-bstr_mole_balance and expand the summation.
$$
\frac{dn_i}{dt} = V \sum_j \nu_{i,j}r_j \quad \Rightarrow \quad \frac{dn_i}{dt} = V \nu_{i,1}r_1
$$

Start with eq-bstr_energy_balance
$$
\left(\sum_i n_i \hat C_{p,i} \right) \frac{dT}{dt} - V\frac{dP}{dt}  - P  \frac{dV}{dt}  = \dot Q - \dot W - V \sum_j \left(r_j \Delta H_j \right)
$$

eq-bstr_diff_eqn_state
$$
\quad V \frac{dP}{dt} - R \left( T \sum_i \frac{dn_i}{dt} + \left( \sum_i n_i \right) \frac{dT}{dt} \right) = 0
$$

