rule reb_J_6_3:
    input:
        "reb_J_6_3/matlab/Vdot_results.csv",
        "reb_J_6_3/matlab/profile_results.csv",
        "reb_J_6_3/python/Vdot_results.csv",
        "reb_J_6_3/python/profile_results.csv",
        "../RE_Basics/examples/reb_J_6_3/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_3/equations.qmd",
        "../RE_Basics/examples/reb_J_6_3/Vdot_results.csv",
        "../RE_Basics/examples/reb_J_6_3/profile_results.csv",
        "../SCoRE/reb_examples/reb_J_6_3/reb_J_6_3.py",
        "../SCoRE/reb_examples/reb_J_6_3/reb_J_6_3.m"

rule reb_J_6_3_python:
    input:
        "reb_J_6_3/python/reb_J_6_3.py"
    output:
        "reb_J_6_3/python/Vdot_results.csv",
        "reb_J_6_3/python/profile_results.csv"
    shell:
        """
        python reb_J_6_3/python/reb_J_6_3.py
        """

rule reb_J_6_3_matlab:
    input:
        "reb_J_6_3/matlab/reb_J_6_3.m"
    output:
        "reb_J_6_3/matlab/Vdot_results.csv",
        "reb_J_6_3/matlab/profile_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_6_3/matlab');reb_J_6_3;exit"
        """

rule reb_J_6_3_re_basics:
    input:
        "reb_J_6_3/narrative.qmd",
        "reb_J_6_3/equations.qmd",
        "reb_J_6_3/python/Vdot_results.csv",
        "reb_J_6_3/python/profile_results.csv"
    output:
        "../RE_Basics/examples/reb_J_6_3/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_3/equations.qmd",
        "../RE_Basics/examples/reb_J_6_3/Vdot_results.csv",
        "../RE_Basics/examples/reb_J_6_3/profile_results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_J_6_3
        mkdir ../RE_Basics/examples/reb_J_6_3
        cp reb_J_6_3/narrative.qmd ../RE_Basics/examples/reb_J_6_3
        cp reb_J_6_3/equations.qmd ../RE_Basics/examples/reb_J_6_3
        cp reb_J_6_3/python/Vdot_results.csv ../RE_Basics/examples/reb_J_6_3
        cp reb_J_6_3/python/profile_results.csv ../RE_Basics/examples/reb_J_6_3
        """

rule reb_J_6_3_score:
    input:
        "reb_J_6_3/python/reb_J_6_3.py",
        "reb_J_6_3/matlab/reb_J_6_3.m"
    output:
        "../SCoRE/reb_examples/reb_J_6_3/reb_J_6_3.py",
        "../SCoRE/reb_examples/reb_J_6_3/reb_J_6_3.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_J_6_3
        mkdir ../SCoRE/reb_examples/reb_J_6_3
        cp reb_J_6_3/python/reb_J_6_3.py ../SCoRE/reb_examples/reb_J_6_3
        cp reb_J_6_3/matlab/reb_J_6_3.m ../SCoRE/reb_examples/reb_J_6_3
        """
