rule reb_J_6_3:
    input:
        "reb_J_6_3/matlab/results/reb_J_6_3_Vdot_results.csv",
        "reb_J_6_3/matlab/results/reb_J_6_3_profile_results.csv",
        "reb_J_6_3/python/results/reb_J_6_3_Vdot_results.csv",
        "reb_J_6_3/python/results/reb_J_6_3_profile_results.csv",
        "../RE_Basics/problem_statements/reb_J_6_3.qmd",
        "../RE_Basics/results/reb_J_6_3_Vdot_results.csv",
        "../RE_Basics/results/reb_J_6_3_profile_results.csv"

rule reb_J_6_3_python:
    input:
        "reb_J_6_3/python/code/reb_J_6_3.py"
    output:
        "reb_J_6_3/python/results/reb_J_6_3_Vdot_results.csv",
        "reb_J_6_3/python/results/reb_J_6_3_profile_results.csv"
    shell:
        """
        python reb_J_6_3/python/code/reb_J_6_3.py
        """

rule reb_J_6_3_matlab:
    input:
        "reb_J_6_3/matlab/code/reb_J_6_3.m"
    output:
        "reb_J_6_3/matlab/results/reb_J_6_3_Vdot_results.csv",
        "reb_J_6_3/matlab/results/reb_J_6_3_profile_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_6_3/matlab/code');\
        reb_J_6_3;exit"
        """

rule reb_J_6_3_re_basics:
    input:
        "reb_J_6_3/problem_statement.qmd",
        "reb_J_6_3/python/results/reb_J_6_3_Vdot_results.csv",
        "reb_J_6_3/python/results/reb_J_6_3_profile_results.csv"
    output:
        "../RE_Basics/problem_statements/reb_J_6_3.qmd",
        "../RE_Basics/results/reb_J_6_3_Vdot_results.csv",
        "../RE_Basics/results/reb_J_6_3_profile_results.csv"
    shell:
        """
        cp reb_J_6_3/problem_statement.qmd ../RE_Basics/problem_statements/reb_J_6_3.qmd
        cp reb_J_6_3/python/results/reb_J_6_3_Vdot_results.csv ../RE_Basics/results/reb_J_6_3_Vdot_results.csv
        cp reb_J_6_3/python/results/reb_J_6_3_profile_results.csv ../RE_Basics/results/reb_J_6_3_profile_results.csv
        """