rule reb_19_5_1:
    input:
        "reb_19_5_1/python/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_data_65.csv",
        "reb_19_5_1/python/reb_19_5_1_data_73.csv",
        "reb_19_5_1/python/reb_19_5_1_data_82.csv",
        "reb_19_5_1/python/reb_19_5_1_data_90.csv",
        "reb_19_5_1/python/reb_19_5_1_data_filenames.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_params.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_90.png",
        "reb_19_5_1/python/reb_19_5_1_model_65.png",
        "reb_19_5_1/python/reb_19_5_1_model_73.png",
        "reb_19_5_1/python/reb_19_5_1_model_82.png",
        "reb_19_5_1/python/reb_19_5_1_model_90.png",
        "reb_19_5_1/python/reb_19_5_1_diff_params.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.png",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_data.csv",
        "../RE_Basics/examples/reb_19_5_1/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_1/equations.qmd",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_params.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_diff_params.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_resp_fcn.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_resp_fcn.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_diff.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_diff.png",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_create_data_blocks.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_65.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_73.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_82.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_90.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_filenames.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_resp_fcn.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_diff.py"

rule reb_19_5_1_python:
    input:
        "reb_19_5_1/python/reb_19_5_1_data_generator.py",
        "reb_19_5_1/python/reb_19_5_1_create_data_blocks.py",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn.py",
        "reb_19_5_1/python/reb_19_5_1_diff.py",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius.py"
    output:
        "reb_19_5_1/python/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_data_65.csv",
        "reb_19_5_1/python/reb_19_5_1_data_73.csv",
        "reb_19_5_1/python/reb_19_5_1_data_82.csv",
        "reb_19_5_1/python/reb_19_5_1_data_90.csv",
        "reb_19_5_1/python/reb_19_5_1_data_filenames.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_params.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_90.png",
        "reb_19_5_1/python/reb_19_5_1_model_65.png",
        "reb_19_5_1/python/reb_19_5_1_model_73.png",
        "reb_19_5_1/python/reb_19_5_1_model_82.png",
        "reb_19_5_1/python/reb_19_5_1_model_90.png",
        "reb_19_5_1/python/reb_19_5_1_diff_params.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.png",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.png"
        ""
    shell:
        """
        python3 reb_19_5_1/python/reb_19_5_1_data_generator.py
        python3 reb_19_5_1/python/reb_19_5_1_create_data_blocks.py
        python3 reb_19_5_1/python/reb_19_5_1_resp_fcn.py
        python3 reb_19_5_1/python/reb_19_5_1_diff.py
        python3 reb_19_5_1/python/reb_19_5_1_Arrhenius.py
        """

rule reb_19_5_1_matlab:
    input:
    output:
    shell:
        """
        """

rule reb_19_5_1_re_basics:
    input:
        "reb_19_5_1/narrative.qmd",
        "reb_19_5_1/equations.qmd",
        "reb_19_5_1/python/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_params.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_65.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_73.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_82.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_90.png",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_90.png",
        "reb_19_5_1/python/reb_19_5_1_model_65.png",
        "reb_19_5_1/python/reb_19_5_1_model_73.png",
        "reb_19_5_1/python/reb_19_5_1_model_82.png",
        "reb_19_5_1/python/reb_19_5_1_model_90.png",
        "reb_19_5_1/python/reb_19_5_1_diff_params.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.png",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.csv",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.png"
    output:
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_data.csv",
        "../RE_Basics/examples/reb_19_5_1/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_1/equations.qmd",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_params.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_diff_params.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_model_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_65.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_73.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_82.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_parity_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_CA0_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_resp_fcn_residual_tf_90.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_resp_fcn.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_resp_fcn.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_diff.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_Arrhenius_diff.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_19_5_1
        mkdir ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/narrative.qmd ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/equations.qmd ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_params.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_65.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_65.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_65.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_73.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_73.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_73.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_82.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_82.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_82.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_parity_90.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_CA0_90.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn_residual_tf_90.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_model_65.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_model_73.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_model_82.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_model_90.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_diff_params.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_Arrhenius_resp_fcn.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_Arrhenius_diff.png ../RE_Basics/examples/reb_19_5_1
        """

rule reb_19_5_1_score:
    input:
        "reb_19_5_1/python/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_create_data_blocks.py",
        "reb_19_5_1/python/reb_19_5_1_data_65.csv",
        "reb_19_5_1/python/reb_19_5_1_data_73.csv",
        "reb_19_5_1/python/reb_19_5_1_data_82.csv",
        "reb_19_5_1/python/reb_19_5_1_data_90.csv",
        "reb_19_5_1/python/reb_19_5_1_data_filenames.csv",
        "reb_19_5_1/python/reb_19_5_1_resp_fcn.py",
        "reb_19_5_1/python/reb_19_5_1_diff.py",
        "reb_19_5_1/python/reb_19_5_1_Arrhenius.py"
    output:
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_create_data_blocks.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_65.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_73.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_82.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_90.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data_filenames.csv",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_resp_fcn.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_diff.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_Arrhenius.py"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_19_5_1
        mkdir ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_create_data_blocks.py ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data_65.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data_73.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data_82.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data_90.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_data_filenames.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_resp_fcn.py ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_diff.py ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_Arrhenius.py ../SCoRE/reb_examples/reb_19_5_1
        """

