rule reb_19_5_1:
    input:
        "reb_19_5_1/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_results.csv",
        "reb_19_5_1/python/reb_19_5_1_parity.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_CA0.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_tf.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_T.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_data.csv",
        "../RE_Basics/examples/reb_19_5_1/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_1/equations.qmd",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_results.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_parity.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_CA0.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_tf.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_T.png",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1.m",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data.csv"

rule reb_19_5_1_python:
    input:
        "reb_19_5_1/python/reb_19_5_1_data_generator.py",
        "reb_19_5_1/python/reb_19_5_1.py"
    output:
        "reb_19_5_1/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_results.csv",
        "reb_19_5_1/python/reb_19_5_1_parity.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_CA0.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_tf.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_T.png"
    shell:
        """
        python3 reb_19_5_1/python/reb_19_5_1_data_generator.py
        python3 reb_19_5_1/python/reb_19_5_1.py
        """

rule reb_19_5_1_matlab:
    input:
        "reb_19_5_1/matlab/reb_19_5_1.m"
    output:
        "reb_19_5_1/matlab/reb_19_5_1_results.csv",
        "reb_19_5_1/matlab/reb_19_5_1_parity_65.png",
        "reb_19_5_1/matlab/reb_19_5_1_residuals_CA0.png",
        "reb_19_5_1/matlab/reb_19_5_1_residuals_tf.png",
        "reb_19_5_1/matlab/reb_19_5_1_residuals_T.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_19_5_1/matlab');reb_19_5_1;exit"
        """

rule reb_19_5_1_re_basics:
    input:
        "reb_19_5_1/narrative.qmd",
        "reb_19_5_1/equations.qmd",
        "reb_19_5_1/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1_results.csv",
        "reb_19_5_1/python/reb_19_5_1_parity.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_CA0.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_tf.png",
        "reb_19_5_1/python/reb_19_5_1_residuals_T.png"
    output:
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_data.csv",
        "../RE_Basics/examples/reb_19_5_1/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_1/equations.qmd",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_results.csv",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_parity.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_CA0.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_tf.png",
        "../RE_Basics/examples/reb_19_5_1/reb_19_5_1_residuals_T.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_19_5_1
        mkdir ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/narrative.qmd ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/equations.qmd ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/reb_19_5_1_data.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_results.csv ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_parity.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_residuals_CA0.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_residuals_tf.png ../RE_Basics/examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1_residuals_T.png ../RE_Basics/examples/reb_19_5_1
        """

rule reb_19_5_1_score:
    input:
        "reb_19_5_1/reb_19_5_1_data.csv",
        "reb_19_5_1/python/reb_19_5_1.py",
        "reb_19_5_1/matlab/reb_19_5_1.m"
    output:
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1.py",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1.m",
        "../SCoRE/reb_examples/reb_19_5_1/reb_19_5_1_data.csv"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_19_5_1
        mkdir ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/reb_19_5_1_data.csv ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/python/reb_19_5_1.py ../SCoRE/reb_examples/reb_19_5_1
        cp reb_19_5_1/matlab/reb_19_5_1.m ../SCoRE/reb_examples/reb_19_5_1
        """

