rule reb_9_6_1:
    input:
        "reb_9_6_1/matlab/results/reb_9_6_1_results.csv",
        "reb_9_6_1/matlab/results/reb_9_6_1_concentrations.png",
        "reb_9_6_1/matlab/results/reb_9_6_1_temperature.png",
        "reb_9_6_1/matlab/results/reb_9_6_1_rate.png",
        "reb_9_6_1/python/results/reb_9_6_1_results.csv",
        "reb_9_6_1/python/results/reb_9_6_1_concentrations.png",
        "reb_9_6_1/python/results/reb_9_6_1_temperature.png",
        "reb_9_6_1/python/results/reb_9_6_1_rate.png",
        "../RE_Basics/Graphics/reb_9_6_1_concentrations.png",
        "../RE_Basics/Graphics/reb_9_6_1_temperature.png",
        "../RE_Basics/Graphics/reb_9_6_1_rate.png"

rule reb_9_6_1_python:
    input:
        "reb_9_6_1/python/code/reb_9_6_1_calculations.py"
    output:
        "reb_9_6_1/python/results/reb_9_6_1_results.csv",
        "reb_9_6_1/python/results/reb_9_6_1_concentrations.png",
        "reb_9_6_1/python/results/reb_9_6_1_temperature.png",
        "reb_9_6_1/python/results/reb_9_6_1_rate.png",
        "../RE_Basics/Graphics/reb_9_6_1_concentrations.png",
        "../RE_Basics/Graphics/reb_9_6_1_temperature.png",
        "../RE_Basics/Graphics/reb_9_6_1_rate.png"
    shell:
        """
        python3 reb_9_6_1/python/code/reb_9_6_1_calculations.py
        cp reb_9_6_1/python/results/reb_9_6_1_concentrations.png ../RE_Basics/Graphics
        cp reb_9_6_1/Results/reb_9_6_1_rate.png ../RE_Basics/Graphics
        cp reb_9_6_1/Results/reb_9_6_1_temperature.png ../RE_Basics/Graphics
        """

rule reb_9_6_1_matlab:
    input:
        "reb_9_6_1/matlab/code/reb_9_6_1_calculations.m"
    output:
        "reb_9_6_1/matlab/results/reb_9_6_1_results.csv",
        "reb_9_6_1/matlab/results/reb_9_6_1_concentrations.png",
        "reb_9_6_1/matlab/results/reb_9_6_1_temperature.png",
        "reb_9_6_1/matlab/results/reb_9_6_1_rate.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_9_6_1/matlab/code');\
        reb_9_6_1_calculations;exit"
        """