rule reb_L_7_2:
    input:
        "reb_L_7_2/python/results.csv",
        "reb_L_7_2/python/parity_plot.png",
        "reb_L_7_2/python/residuals_vs_tf_plot.png",
        "reb_L_7_2/matlab/results.csv",
        "reb_L_7_2/matlab/parity_plot.png",
        "reb_L_7_2/matlab/residuals_vs_tf_plot.png",
        "../RE_Basics/examples/reb_L_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_L_7_2/reb_L_7_2_data.csv",
        "../RE_Basics/examples/reb_L_7_2/results.csv",
        "../RE_Basics/examples/reb_L_7_2/parity_plot.png",
        "../RE_Basics/examples/reb_L_7_2/residuals_vs_tf_plot.png",
        "../SCoRE/reb_examples/reb_L_7_2/reb_L_7_2.m",
        "../SCoRE/reb_examples/reb_L_7_2/reb_L_7_2.py"

rule reb_L_7_2_python:
    input:
        "reb_L_7_2/python/reb_L_7_2.py"
    output:
        "reb_L_7_2/python/results.csv",
        "reb_L_7_2/python/parity_plot.png",
        "reb_L_7_2/python/residuals_vs_tf_plot.png"
    shell:
        """
        python3 reb_L_7_2/python/reb_L_7_2.py"
        """

rule reb_L_7_2_matlab:
    input:
        "reb_L_7_2/matlab/reb_L_7_2.m"
    output:
        "reb_L_7_2/matlab/results.csv",
        "reb_L_7_2/matlab/parity_plot.png",
        "reb_L_7_2/matlab/residuals_vs_tf_plot.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_L_7_2/matlab');reb_L_7_2;exit"
        """

rule reb_L_7_2_re_basics:
    input:
        "reb_L_7_2/narrative.qmd",
        "reb_L_7_2/reb_L_7_2_data.csv",
        "reb_L_7_2/python/results.csv",
        "reb_L_7_2/python/parity_plot.png",
        "reb_L_7_2/python/residuals_vs_tf_plot.png"
    output:
        "../RE_Basics/examples/reb_L_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_L_7_2/reb_L_7_2_data.csv",
        "../RE_Basics/examples/reb_L_7_2/results.csv",
        "../RE_Basics/examples/reb_L_7_2/parity_plot.png",
        "../RE_Basics/examples/reb_L_7_2/residuals_vs_tf_plot.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_L_7_2
        mkdir ../RE_Basics/examples/reb_L_7_2
        cp reb_L_7_2/narrative.qmd ../RE_Basics/examples/reb_L_7_2
        cp reb_L_7_2/reb_L_7_2_data.csv ../RE_Basics/examples/reb_L_7_2
        cp reb_L_7_2/python/results.csv ../RE_Basics/examples/reb_L_7_2
        cp reb_L_7_2/python/parity_plot.png ../RE_Basics/examples/reb_L_7_2
        cp reb_L_7_2/python/residuals_vs_tf_plot.png ../RE_Basics/examples/reb_L_7_2
        """
rule reb_L_7_2_score:
    input:
        "reb_L_7_2/python/reb_L_7_2.py",
        "reb_L_7_2/matlab/reb_L_7_2.m"
    output:
        "../SCoRE/reb_examples/reb_L_7_2/reb_L_7_2.m",
        "../SCoRE/reb_examples/reb_L_7_2/reb_L_7_2.py"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_L_7_2
        mkdir ../SCoRE/reb_examples/reb_L_7_2
        cp reb_L_7_2/python/reb_L_7_2.py ../SCoRE/reb_examples/reb_L_7_2
        cp reb_L_7_2/matlab/reb_L_7_2.m ../SCoRE/reb_examples/reb_L_7_2
        """
