rule reb_10_5_2:
    input:
        "reb_10_5_2/matlab/results.csv",
        "reb_10_5_2/python/results.csv",
        "reb_10_5_2/python/discussion.csv",
        "../RE_Basics/examples/reb_10_5_2/results.csv",
        "../RE_Basics/examples/reb_10_5_2/discussion.csv",
        "../RE_Basics/examples/reb_10_5_2/narrative.qmd",
        "../RE_Basics/examples/reb_10_5_2/equations.qmd",
        "../SCoRE/reb_examples/reb_10_5_2/reb_10_5_2.py",
        "../SCoRE/reb_examples/reb_10_5_2/reb_10_5_2.m"

rule reb_10_5_2_python:
    input:
        "reb_10_5_2/python/reb_10_5_2.py",
        "reb_10_5_2/python/reb_10_5_2_discussion.py"
    output:
        "reb_10_5_2/python/results.csv",
        "reb_10_5_2/python/discussion.csv"
    shell:
        """
        python3 reb_10_5_2/python/reb_10_5_2.py
        python3 reb_10_5_2/python/reb_10_5_2_discussion.py
        """

rule reb_10_5_2_matlab:
    input:
        "reb_10_5_2/matlab/reb_10_5_2.m"
    output:
        "reb_10_5_2/matlab/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_10_5_2/matlab');reb_10_5_2;exit"
        """

rule reb_10_5_2_re_basics:
    input:
        "reb_10_5_2/python/results.csv",
        "reb_10_5_2/python/discussion.csv",
        "reb_10_5_2/narrative.qmd",
        "reb_10_5_2/equations.qmd"
    output:
        "../RE_Basics/examples/reb_10_5_2/results.csv",
        "../RE_Basics/examples/reb_10_5_2/discussion.csv",
        "../RE_Basics/examples/reb_10_5_2/narrative.qmd",
        "../RE_Basics/examples/reb_10_5_2/equations.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_10_5_2
        mkdir ../RE_Basics/examples/reb_10_5_2
        cp reb_10_5_2/python/results.csv ../RE_Basics/examples/reb_10_5_2
        cp reb_10_5_2/python/discussion.csv ../RE_Basics/examples/reb_10_5_2
        cp reb_10_5_2/narrative.qmd ../RE_Basics/examples/reb_10_5_2
        cp reb_10_5_2/equations.qmd ../RE_Basics/examples/reb_10_5_2
        """

rule reb_10_5_2_score:
    input:
        "reb_10_5_2/python/reb_10_5_2.py",
        "reb_10_5_2/matlab/reb_10_5_2.m"
    output:
        "../SCoRE/reb_examples/reb_10_5_2/reb_10_5_2.py",
        "../SCoRE/reb_examples/reb_10_5_2/reb_10_5_2.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_10_5_2
        mkdir ../SCoRE/reb_examples/reb_10_5_2
        cp reb_10_5_2/python/reb_10_5_2.py ../SCoRE/reb_examples/reb_10_5_2
        cp reb_10_5_2/matlab/reb_10_5_2.m ../SCoRE/reb_examples/reb_10_5_2
        """
