rule reb_11_3:
    input:
        "reb_11_3/Data/reb_11_3_data.csv",
        "../RE_Basics/Data/reb_11_3_data.csv",
        "reb_11_3/Results/reb_11_3_results.csv",
        "reb_11_3/Results/reb_11_3_parity.png",
        "reb_11_3/Results/reb_11_3_VFR_residuals.png",
        "reb_11_3/Results/reb_11_3_CA_residuals.png",
        "reb_11_3/Results/reb_11_3_CY_residuals.png",
        "reb_11_3/Results/reb_11_3_CZ_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_parity.png",
        "../RE_Basics/Graphics/reb_11_3_VFR_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CA_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CY_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CZ_residuals.png"

rule reb_11_3_data:
    input: 
        "reb_11_3/Code/reb_11_3_cstr_data_generator.py"
    output:
        "reb_11_3/Data/reb_11_3_data.csv",
        "../RE_Basics/Data/reb_11_3_data.csv",
    shell:
        """
        python3 reb_11_3/Code/reb_11_3_cstr_data_generator.py
        """

rule reb_11_3_results:
    input:
        "reb_11_3/Code/reb_11_3_calculations.py",
        "reb_11_3/Code/response_function.py",
        "reb_11_3/Data/reb_11_3_data.csv"
    output:
        "reb_11_3/Results/reb_11_3_results.csv",
        "reb_11_3/Results/reb_11_3_parity.png",
        "reb_11_3/Results/reb_11_3_VFR_residuals.png",
        "reb_11_3/Results/reb_11_3_CA_residuals.png",
        "reb_11_3/Results/reb_11_3_CY_residuals.png",
        "reb_11_3/Results/reb_11_3_CZ_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_parity.png",
        "../RE_Basics/Graphics/reb_11_3_VFR_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CA_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CY_residuals.png",
        "../RE_Basics/Graphics/reb_11_3_CZ_residuals.png"
    shell:
        """
        python3 reb_11_3/Code/reb_11_3_calculations.py
        """