rule reb_10_3:
    input:
        "reb_10_3/Data/reb_10_3_data.csv",
        "../RE_Basics/Data/reb_10_3_data.csv",
        "reb_10_3/Results/reb_10_3_results.csv",
        "reb_10_3/Results/reb_10_3_parity.png",
        "reb_10_3/Results/reb_10_3_VFR_residuals.png",
        "reb_10_3/Results/reb_10_3_CA_residuals.png",
        "reb_10_3/Results/reb_10_3_CY_residuals.png",
        "reb_10_3/Results/reb_10_3_CZ_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_parity.png",
        "../RE_Basics/Graphics/reb_10_3_VFR_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CA_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CY_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CZ_residuals.png"

rule reb_10_3_data:
    input: 
        "reb_10_3/Code/reb_10_3_cstr_data_generator.py"
    output:
        "reb_10_3/Data/reb_10_3_data.csv",
        "../RE_Basics/Data/reb_10_3_data.csv",
    shell:
        """
        python3 reb_10_3/Code/reb_10_3_cstr_data_generator.py
        """

rule reb_10_3_results:
    input:
        "reb_10_3/Code/reb_10_3_calculations.py",
        "reb_10_3/Code/response_function.py",
        "reb_10_3/Data/reb_10_3_data.csv"
    output:
        "reb_10_3/Results/reb_10_3_results.csv",
        "reb_10_3/Results/reb_10_3_parity.png",
        "reb_10_3/Results/reb_10_3_VFR_residuals.png",
        "reb_10_3/Results/reb_10_3_CA_residuals.png",
        "reb_10_3/Results/reb_10_3_CY_residuals.png",
        "reb_10_3/Results/reb_10_3_CZ_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_parity.png",
        "../RE_Basics/Graphics/reb_10_3_VFR_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CA_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CY_residuals.png",
        "../RE_Basics/Graphics/reb_10_3_CZ_residuals.png"
    shell:
        """
        python3 reb_10_3/Code/reb_10_3_calculations.py
        """