rule reb_9_4:
    input: 
        "reb_9_4/Data/reb_9_4_data.csv",
        "../RE_Basics/Data/reb_9_4_data.csv",
        "reb_9_4/Results/reb_9_4_results.csv",
        "reb_9_4/Results/reb_9_4_parity.png",
        "reb_9_4/Results/reb_9_4_residuals_vs_CS0.png",
        "reb_9_4/Results/reb_9_4_residuals_vs_t.png",
        "../RE_Basics/Graphics/reb_9_4_parity.png",
        "../RE_Basics/Graphics/reb_9_4_residuals_vs_CS0.png",
        "../RE_Basics/Graphics/reb_9_4_residuals_vs_t.png"

rule reb_9_4_data:
    input: "reb_9_4/Code/reb_9_4_bstr_data_generator.py"
    output:
        "reb_9_4/Data/reb_9_4_data.csv",
        "../RE_Basics/Data/reb_9_4_data.csv"
    shell:
        """
        python3 reb_9_4/Code/reb_9_4_bstr_data_generator.py
        """

rule reb_9_4_results:
    input:
        "reb_9_4/Data/reb_9_4_data.csv",
        "reb_9_4/Code/reb_9_4_calculations.py",
        "reb_9_4/Code/response_function.py"
    output:
        "reb_9_4/Results/reb_9_4_results.csv",
        "reb_9_4/Results/reb_9_4_parity.png",
        "reb_9_4/Results/reb_9_4_residuals_vs_CS0.png",
        "reb_9_4/Results/reb_9_4_residuals_vs_t.png",
        "../RE_Basics/Graphics/reb_9_4_parity.png",
        "../RE_Basics/Graphics/reb_9_4_residuals_vs_CS0.png",
        "../RE_Basics/Graphics/reb_9_4_residuals_vs_t.png"
    shell:
        """
        python3 reb_9_4/Code/reb_9_4_calculations.py
        """