rule reb_9_3:
    input: 
        "reb_9_3/Data/reb_9_3_data.csv",
        "../RE_Basics/Data/reb_9_3_data.csv",
        "reb_9_3/Results/reb_9_3_results.csv",
        "reb_9_3/Results/reb_9_3_parity.png",
        "reb_9_3/Results/reb_9_3_PA0_residuals.png",
        "reb_9_3/Results/reb_9_3_t_residuals.png",
        "../RE_Basics/Graphics/reb_9_3_parity.png",
        "../RE_Basics/Graphics/reb_9_3_PA0_residuals.png",
        "../RE_Basics/Graphics/reb_9_3_t_residuals.png"

rule reb_9_3_data:
    input: "reb_9_3/Code/reb_9_3_bstr_data_generator.py"
    output:
        "reb_9_3/Data/reb_9_3_data.csv",
        "../RE_Basics/Data/reb_9_3_data.csv"
    shell:
        """
        python3 reb_9_3/Code/reb_9_3_bstr_data_generator.py
        """

rule reb_9_3_results:
    input:
        "reb_9_3/Data/reb_9_3_data.csv",
        "reb_9_3/Code/reb_9_3_calculations.py",
        "reb_9_3/Code/response_function.py"
    output:
        "reb_9_3/Results/reb_9_3_results.csv",
        "reb_9_3/Results/reb_9_3_parity.png",
        "reb_9_3/Results/reb_9_3_PA0_residuals.png",
        "reb_9_3/Results/reb_9_3_t_residuals.png",
        "../RE_Basics/Graphics/reb_9_3_parity.png",
        "../RE_Basics/Graphics/reb_9_3_PA0_residuals.png",
        "../RE_Basics/Graphics/reb_9_3_t_residuals.png"
    shell:
        """
        python3 reb_9_3/Code/reb_9_3_calculations.py
        """