rule reb_K_3:
    input:
        "reb_K_3/matlab/results/reb_K_3_results.csv",
        "reb_K_3/python/results/reb_K_3_results.csv"

rule reb_K_3_python:
    input:
        "reb_K_3/python/code/reb_K_3_calculations.py"
    output:
        "reb_K_3/python/results/reb_K_3_results.csv"
    shell:
        """
        python reb_K_3/python/code/reb_K_3_calculations.py
        """

rule reb_K_3_matlab:
    input:
        "reb_K_3/matlab/code/reb_K_3_calculations.m"
    output:
        "reb_K_3/matlab/results/reb_K_3_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_K_3/matlab/code');\
        reb_K_3_calculations;exit"
        """