rule reb_17_3_2:
    input:
#        "reb_17_3_2/python/results.csv",
#        "reb_17_3_2/matlab/results.csv",
        "../RE_Basics/examples/reb_17_3_2/narrative.qmd",
        "../RE_Basics/examples/reb_17_3_2/equations.qmd",
        "../RE_Basics/examples/reb_17_3_2/given.qmd"
#        "../RE_Basics/examples/reb_17_3_2/results.csv",
#        "../SCoRE/reb_examples/reb_17_3_2/reb_17_3_2.py",
#        "../SCoRE/reb_examples/reb_17_3_2/reb_17_3_2.m"

rule reb_17_3_2_python:
    input:
#        "reb_17_3_2/python/reb_17_3_2.py"
    output:
#        "reb_17_3_2/python/results.csv"
    shell:
        """
        
        """

rule reb_17_3_2_matlab:
    input:
#        "reb_17_3_2/matlab/reb_17_3_2.m"
    output:
#       "reb_17_3_2/matlab/results.csv"
    shell:
        """
        
        """

rule reb_17_3_2_re_basics:
    input:
        "reb_17_3_2/narrative.qmd",
        "reb_17_3_2/equations.qmd",
        "reb_17_3_2/given.qmd"
#        "reb_17_3_2/python/results.csv"
    output:
        "../RE_Basics/examples/reb_17_3_2/narrative.qmd",
        "../RE_Basics/examples/reb_17_3_2/equations.qmd",
        "../RE_Basics/examples/reb_17_3_2/given.qmd"
#        "../RE_Basics/examples/reb_17_3_2/results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_17_3_2
        mkdir ../RE_Basics/examples/reb_17_3_2
        cp reb_17_3_2/narrative.qmd ../RE_Basics/examples/reb_17_3_2
        cp reb_17_3_2/equations.qmd ../RE_Basics/examples/reb_17_3_2
        cp reb_17_3_2/given.qmd ../RE_Basics/examples/reb_17_3_2
        """

rule reb_17_3_2_score:
    input:
#        "reb_17_3_2/python/reb_17_3_2.py",
#        "reb_17_3_2/matlab/reb_17_3_2.m"
    output:
#        "../SCoRE/reb_examples/reb_17_3_2/reb_17_3_2.py",
#        "../SCoRE/reb_examples/reb_17_3_2/reb_17_3_2.m"
    shell:
        """
        
        """
