rule reb_J_6_1:
    input:
        "reb_J_6_1/python/results.csv",
        "reb_J_6_1/matlab/results.csv",
        "../RE_Basics/examples/reb_J_6_1/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_1/equations.qmd",
        "../RE_Basics/examples/reb_J_6_1/results.csv",
        "../SCoRE/reb_examples/reb_J_6_1/reb_J_6_1.py",
        "../SCoRE/reb_examples/reb_J_6_1/reb_J_6_1.m"

rule reb_J_6_1_python:
    input:
        "reb_J_6_1/python/reb_J_6_1.py"
    output:
        "reb_J_6_1/python/results.csv"
    shell:
        """
        python reb_J_6_1/python/reb_J_6_1.py
        """

rule reb_J_6_1_matlab:
    input:
        "reb_J_6_1/matlab/reb_J_6_1.m"
    output:
        "reb_J_6_1/matlab/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_6_1/matlab');reb_J_6_1;exit"
        """

rule reb_J_6_1_re_basics:
    input:
        "reb_J_6_1/narrative.qmd",
        "reb_J_6_1/equations.qmd",
        "reb_J_6_1/python/results.csv",
        "reb_J_6_1/python/reb_J_6_1.py",
        "reb_J_6_1/matlab/reb_J_6_1.m"
    output:
        "../RE_Basics/examples/reb_J_6_1/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_1/equations.qmd",
        "../RE_Basics/examples/reb_J_6_1/results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_J_6_1
        mkdir ../RE_Basics/examples/reb_J_6_1
        cp reb_J_6_1/narrative.qmd ../RE_Basics/examples/reb_J_6_1/narrative.qmd
        cp reb_J_6_1/equations.qmd ../RE_Basics/examples/reb_J_6_1/equations.qmd
        cp reb_J_6_1/python/results.csv ../RE_Basics/examples/reb_J_6_1/results.csv
        """

rule reb_J_6_1_score:
    input:
        "reb_J_6_1/python/reb_J_6_1.py",
        "reb_J_6_1/matlab/reb_J_6_1.m"
    output:
        "../SCoRE/reb_examples/reb_J_6_1/reb_J_6_1.py",
        "../SCoRE/reb_examples/reb_J_6_1/reb_J_6_1.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_J_6_1
        mkdir ../SCoRE/reb_examples/reb_J_6_1
        cp reb_J_6_1/python/reb_J_6_1.py ../SCoRE/reb_examples/reb_J_6_1
        cp reb_J_6_1/matlab/reb_J_6_1.m ../SCoRE/reb_examples/reb_J_6_1
        """
