rule reb_20_5_2:
    input:
        "reb_20_5_2/reb_20_5_2_data.csv",
        "reb_20_5_2/python/reb_20_5_2_results.csv",
        "reb_20_5_2/python/reb_20_5_2_parity.png",
        "reb_20_5_2/python/reb_20_5_2_tau_residual.png",
        "reb_20_5_2/python/reb_20_5_2_yA0_residual.png",
        "reb_20_5_2/matlab/reb_20_5_2_results.csv",
        "reb_20_5_2/matlab/reb_20_5_2_parity.png",
        "reb_20_5_2/matlab/reb_20_5_2_tau_residual.png",
        "reb_20_5_2/matlab/reb_20_5_2_yA0_residual.png",
        "../RE_Basics/examples/reb_20_5_2/narrative.qmd",
        "../RE_Basics/examples/reb_20_5_2/equations.qmd",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_data.csv",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_results.csv",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_parity.png",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_tau_residual.png",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_yA0_residual.png",
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2.py",
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2.m",
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2_data.csv"

rule reb_20_5_2_python:
    input:
        "reb_20_5_2/python/reb_20_5_2_cstr_data_generator.py",
        "reb_20_5_2/python/reb_20_5_2.py"
    output:
        "reb_20_5_2/reb_20_5_2_data.csv",
        "reb_20_5_2/python/reb_20_5_2_results.csv",
        "reb_20_5_2/python/reb_20_5_2_parity.png",
        "reb_20_5_2/python/reb_20_5_2_tau_residual.png",
        "reb_20_5_2/python/reb_20_5_2_yA0_residual.png"
    shell:
        """
        python3 reb_20_5_2/python/reb_20_5_2_cstr_data_generator.py
        python3 reb_20_5_2/python/reb_20_5_2.py
        """

rule reb_20_5_2_matlab:
    input:
        "reb_20_5_2/matlab/reb_20_5_2.m"
    output:
        "reb_20_5_2/matlab/reb_20_5_2_results.csv",
        "reb_20_5_2/matlab/reb_20_5_2_parity.png",
        "reb_20_5_2/matlab/reb_20_5_2_tau_residual.png",
        "reb_20_5_2/matlab/reb_20_5_2_yA0_residual.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_20_5_2/matlab');reb_20_5_2;exit"
        """

rule reb_20_5_2_re_basics:
    input:
        "reb_20_5_2/narrative.qmd",
        "reb_20_5_2/equations.qmd",
        "reb_20_5_2/reb_20_5_2_data.csv",
        "reb_20_5_2/python/reb_20_5_2_results.csv",
        "reb_20_5_2/python/reb_20_5_2_parity.png",
        "reb_20_5_2/python/reb_20_5_2_tau_residual.png",
        "reb_20_5_2/python/reb_20_5_2_yA0_residual.png"
    output:
        "../RE_Basics/examples/reb_20_5_2/narrative.qmd",
        "../RE_Basics/examples/reb_20_5_2/equations.qmd",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_data.csv",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_results.csv",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_parity.png",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_tau_residual.png",
        "../RE_Basics/examples/reb_20_5_2/reb_20_5_2_yA0_residual.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_20_5_2
        mkdir ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/narrative.qmd ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/equations.qmd ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/reb_20_5_2_data.csv ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/python/reb_20_5_2_results.csv ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/python/reb_20_5_2_parity.png ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/python/reb_20_5_2_tau_residual.png ../RE_Basics/examples/reb_20_5_2
        cp reb_20_5_2/python/reb_20_5_2_yA0_residual.png ../RE_Basics/examples/reb_20_5_2
        """

rule reb_20_5_2_score:
    input:
        "reb_20_5_2/python/reb_20_5_2.py",
        "reb_20_5_2/matlab/reb_20_5_2.m",
        "reb_20_5_2/reb_20_5_2_data.csv"
    output:
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2.py",
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2.m",
        "../SCoRE/reb_examples/reb_20_5_2/reb_20_5_2_data.csv"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_20_5_2
        mkdir ../SCoRE/reb_examples/reb_20_5_2
        cp reb_20_5_2/python/reb_20_5_2.py ../SCoRE/reb_examples/reb_20_5_2
        cp reb_20_5_2/matlab/reb_20_5_2.m ../SCoRE/reb_examples/reb_20_5_2
        cp reb_20_5_2/reb_20_5_2_data.csv ../SCoRE/reb_examples/reb_20_5_2
        """
