rule reb_J_6_2:
    input:
        "reb_J_6_2/matlab/Tin_results.csv",
        "reb_J_6_2/matlab/profile_results.csv",
        "reb_J_6_2/python/Tin_results.csv",
        "reb_J_6_2/python/profile_results.csv",
        "../RE_Basics/examples/reb_J_6_2/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_2/equations.qmd",
        "../RE_Basics/examples/reb_J_6_2/Tin_results.csv",
        "../RE_Basics/examples/reb_J_6_2/profile_results.csv",
        "../SCoRE/reb_examples/reb_J_6_2/reb_J_6_2.py",
        "../SCoRE/reb_examples/reb_J_6_2/reb_J_6_2.m"

rule reb_J_6_2_python:
    input:
        "reb_J_6_2/python/reb_J_6_2.py"
    output:
        "reb_J_6_2/python/Tin_results.csv",
        "reb_J_6_2/python/profile_results.csv"
    shell:
        """
        python reb_J_6_2/python/reb_J_6_2.py
        """

rule reb_J_6_2_matlab:
    input:
        "reb_J_6_2/matlab/reb_J_6_2.m"
    output:
        "reb_J_6_2/matlab/Tin_results.csv",
        "reb_J_6_2/matlab/profile_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_6_2/matlab');reb_J_6_2;exit"
        """

rule reb_J_6_2_re_basics:
    input:
        "reb_J_6_2/narrative.qmd",
        "reb_J_6_2/equations.qmd",
        "reb_J_6_2/python/Tin_results.csv",
        "reb_J_6_2/python/profile_results.csv"
    output:
        "../RE_Basics/examples/reb_J_6_2/narrative.qmd",
        "../RE_Basics/examples/reb_J_6_2/equations.qmd",
        "../RE_Basics/examples/reb_J_6_2/Tin_results.csv",
        "../RE_Basics/examples/reb_J_6_2/profile_results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_J_6_2
        mkdir ../RE_Basics/examples/reb_J_6_2
        cp reb_J_6_2/narrative.qmd ../RE_Basics/examples/reb_J_6_2/narrative.qmd
        cp reb_J_6_2/equations.qmd ../RE_Basics/examples/reb_J_6_2/equations.qmd
        cp reb_J_6_2/python/Tin_results.csv ../RE_Basics/examples/reb_J_6_2/Tin_results.csv
        cp reb_J_6_2/python/profile_results.csv ../RE_Basics/examples/reb_J_6_2/profile_results.csv
        """

rule reb_J_6_2_score:
    input:
        "reb_J_6_2/python/reb_J_6_2.py",
        "reb_J_6_2/matlab/reb_J_6_2.m"
    output:
        "../SCoRE/reb_examples/reb_J_6_2/reb_J_6_2.py",
        "../SCoRE/reb_examples/reb_J_6_2/reb_J_6_2.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_J_6_2
        mkdir ../SCoRE/reb_examples/reb_J_6_2
        cp reb_J_6_2/python/reb_J_6_2.py ../SCoRE/reb_examples/reb_J_6_2
        cp reb_J_6_2/matlab/reb_J_6_2.m ../SCoRE/reb_examples/reb_J_6_2
        """
