rule reb_J_6_2:
    input:
        "reb_J_6_2/matlab/results/reb_J_6_2_Tin_results.csv",
        "reb_J_6_2/matlab/results/reb_J_6_2_profile_results.csv",
        "reb_J_6_2/python/results/reb_J_6_2_Tin_results.csv",
        "reb_J_6_2/python/results/reb_J_6_2_profile_results.csv",
        "../RE_Basics/problem_statements/reb_J_6_2.qmd",
        "../RE_Basics/results/reb_J_6_2_Tin_results.csv",
        "../RE_Basics/results/reb_J_6_2_profile_results.csv"

rule reb_J_6_2_python:
    input:
        "reb_J_6_2/python/code/reb_J_6_2.py"
    output:
        "reb_J_6_2/python/results/reb_J_6_2_Tin_results.csv",
        "reb_J_6_2/python/results/reb_J_6_2_profile_results.csv"
    shell:
        """
        python reb_J_6_2/python/code/reb_J_6_2.py
        """

rule reb_J_6_2_matlab:
    input:
        "reb_J_6_2/matlab/code/reb_J_6_2.m"
    output:
        "reb_J_6_2/matlab/results/reb_J_6_2_Tin_results.csv",
        "reb_J_6_2/matlab/results/reb_J_6_2_profile_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_6_2/matlab/code');\
        reb_J_6_2;exit"
        """

rule reb_J_6_2_re_basics:
    input:
        "reb_J_6_2/problem_statement.qmd",
        "reb_J_6_2/python/results/reb_J_6_2_Tin_results.csv",
        "reb_J_6_2/python/results/reb_J_6_2_profile_results.csv"
    output:
        "../RE_Basics/problem_statements/reb_J_6_2.qmd",
        "../RE_Basics/results/reb_J_6_2_Tin_results.csv",
        "../RE_Basics/results/reb_J_6_2_profile_results.csv"
    shell:
        """
        cp reb_J_6_2/problem_statement.qmd ../RE_Basics/problem_statements/reb_J_6_2.qmd
        cp reb_J_6_2/python/results/reb_J_6_2_Tin_results.csv ../RE_Basics/results/reb_J_6_2_Tin_results.csv
        cp reb_J_6_2/python/results/reb_J_6_2_profile_results.csv ../RE_Basics/results/reb_J_6_2_profile_results.csv
        """
