rule reb_12_7_2:
    input:
        "reb_12_7_2/matlab/results.csv",
        "reb_12_7_2/python/results.csv",
        "../RE_Basics/examples/reb_12_7_2/results.csv",
        "../RE_Basics/examples/reb_12_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_12_7_2/equations.qmd",
        "../SCoRE/reb_examples/reb_12_7_2/reb_12_7_2.py",
        "../SCoRE/reb_examples/reb_12_7_2/reb_12_7_2.m"

rule reb_12_7_2_python:
    input:
        "reb_12_7_2/python/reb_12_7_2.py"
    output:
        "reb_12_7_2/python/results.csv"
    shell:
        """
        python3 reb_12_7_2/python/reb_12_7_2.py
        """

rule reb_12_7_2_matlab:
    input:
        "reb_12_7_2/matlab/reb_12_7_2.m"
    output:
        "reb_12_7_2/matlab/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_12_7_2/matlab');reb_12_7_2;exit"
        """

rule reb_12_7_2_re_basics:
    input:
        "reb_12_7_2/python/results.csv",
        "reb_12_7_2/narrative.qmd",
        "reb_12_7_2/equations.qmd"
    output:
        "../RE_Basics/examples/reb_12_7_2/results.csv",
        "../RE_Basics/examples/reb_12_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_12_7_2/equations.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_12_7_2
        mkdir ../RE_Basics/examples/reb_12_7_2
        cp reb_12_7_2/python/results.csv ../RE_Basics/examples/reb_12_7_2
        cp reb_12_7_2/narrative.qmd ../RE_Basics/examples/reb_12_7_2
        cp reb_12_7_2/equations.qmd ../RE_Basics/examples/reb_12_7_2
        """

rule reb_12_7_2_score:
    input:
        "reb_12_7_2/python/reb_12_7_2.py",
        "reb_12_7_2/matlab/reb_12_7_2.m"
    output:
        "../SCoRE/reb_examples/reb_12_7_2/reb_12_7_2.py",
        "../SCoRE/reb_examples/reb_12_7_2/reb_12_7_2.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_12_7_2
        mkdir ../SCoRE/reb_examples/reb_12_7_2
        cp reb_12_7_2/python/reb_12_7_2.py ../SCoRE/reb_examples/reb_12_7_2
        cp reb_12_7_2/matlab/reb_12_7_2.m ../SCoRE/reb_examples/reb_12_7_2
        """
