rule reb_24_7_2:
    input:
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_24_7_2/data_table.qmd",
        "../RE_Basics/examples/reb_24_7_2/CSTR_like_CA_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_Like_T_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_like_CA_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_Like_T_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_like_CA_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_Like_T_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_like_CA_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_Like_T_profile_varying_lambda.png"

rule reb_24_7_2_python:
    input:
        
    output:
        
    shell:
        """
        
        """

rule reb_24_7_2_matlab:
    input:
        "reb_24_7_2/matlab/reb_24_7_2.m"
    output:
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_lambda.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_24_7_2/matlab');reb_24_7_2;exit"
        """

rule reb_24_7_2_re_basics:
    input:
        "reb_24_7_2/narrative.qmd",
        "reb_24_7_2/data_table.qmd",
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/CSTR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/CSTR_like_T_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_Dax.png",
        "reb_24_7_2/matlab/PFR_like_CA_profile_varying_lambda.png",
        "reb_24_7_2/matlab/PFR_like_T_profile_varying_lambda.png"
    output:
        "../RE_Basics/examples/reb_24_7_2/narrative.qmd",
        "../RE_Basics/examples/reb_24_7_2/data_table.qmd",
        "../RE_Basics/examples/reb_24_7_2/CSTR_like_CA_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_Like_T_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_like_CA_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/CSTR_Like_T_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_like_CA_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_Like_T_profile_varying_Dax.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_like_CA_profile_varying_lambda.png",
        "../RE_Basics/examples/reb_24_7_2/PFR_Like_T_profile_varying_lambda.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_24_7_2
        mkdir ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/narrative.qmd ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/data_table.qmd ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/CSTR_like_CA_profile_varying_Dax.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/CSTR_like_T_profile_varying_Dax.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/CSTR_like_CA_profile_varying_lambda.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/CSTR_like_T_profile_varying_lambda.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/PFR_like_CA_profile_varying_Dax.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/PFR_like_T_profile_varying_Dax.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/PFR_like_CA_profile_varying_lambda.png ../RE_Basics/examples/reb_24_7_2
        cp reb_24_7_2/matlab/PFR_like_T_profile_varying_lambda.png ../RE_Basics/examples/reb_24_7_2
        """

rule reb_24_7_2_score:
    input:
        
    output:
        
    shell:
        """
        
        """
       