rule reb_K_4_1:
    input:
        "reb_K_4_1/matlab/results.csv",
        "reb_K_4_1/python/results.csv",
        "../RE_Basics/examples/reb_K_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_K_4_1/results.csv",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.m",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.py"
rule reb_K_4_1_python:
    input:
        "reb_K_4_1/python/reb_K_4_1.py"
    output:
        "reb_K_4_1/python/results.csv"
    shell:
        """
        python3 reb_K_4_1/python/reb_K_4_1.py
        """

rule reb_K_4_1_matlab:
    input:
        "reb_K_4_1/matlab/reb_K_4_1.m"
    output:
        "reb_K_4_1/matlab/results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_K_4_1/matlab');reb_K_4_1;exit"
        """

rule reb_K_4_1_re_basics:
    input:
        "reb_K_4_1/narrative.qmd"
    output:
        "../RE_Basics/examples/reb_K_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_K_4_1/results.csv"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_K_4_1
        mkdir ../RE_Basics/examples/reb_K_4_1
        cp reb_K_4_1/narrative.qmd ../RE_Basics/examples/reb_K_4_1
        cp reb_K_4_1/python/results.csv ../RE_Basics/examples/reb_K_4_1
        """

rule reb_K_1_4_score:
    input:
        "reb_K_4_1/matlab/reb_K_4_1.m",
        "reb_K_4_1/python/reb_K_4_1.py"
    output:
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.m",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.py"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_K_4_1
        mkdir ../SCoRE/reb_examples/reb_K_4_1
        cp reb_K_4_1/matlab/reb_K_4_1.m ../SCoRE/reb_examples/reb_K_4_1
        cp reb_K_4_1/python/reb_K_4_1.py ../SCoRE/reb_examples/reb_K_4_1
        """