rule reb_K_4_1:
    input:
        "../RE_Basics/examples/reb_K_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_K_4_1/equations.qmd",
        "../RE_Basics/examples/reb_K_4_1/given.qmd",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.m",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.py"

rule reb_K_4_1_re_basics:
    input:
        "reb_17_3_1/narrative.qmd",
        "reb_17_3_1/equations.qmd",
        "reb_17_3_1/given.qmd"
    output:
        "../RE_Basics/examples/reb_K_4_1/narrative.qmd",
        "../RE_Basics/examples/reb_K_4_1/equations.qmd",
        "../RE_Basics/examples/reb_K_4_1/given.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_K_4_1
        mkdir ../RE_Basics/examples/reb_K_4_1
        cp reb_17_3_1/narrative.qmd ../RE_Basics/examples/reb_K_4_1
        cp reb_17_3_1/equations.qmd ../RE_Basics/examples/reb_K_4_1
        cp reb_17_3_1/given.qmd ../RE_Basics/examples/reb_K_4_1
        """

rule reb_K_1_4_score:
    input:
        "reb_17_3_1/matlab/reb_17_3_1.m",
        "reb_17_3_1/python/reb_17_3_1.py"
    output:
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.m",
        "../SCoRE/reb_examples/reb_K_4_1/reb_K_4_1.py"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_K_4_1
        mkdir ../SCoRE/reb_examples/reb_K_4_1
        cp reb_17_3_1/matlab/reb_17_3_1.m ../SCoRE/reb_examples/reb_K_4_1
        cp reb_17_3_1/python/reb_17_3_1.py ../SCoRE/reb_examples/reb_K_4_1
        """