rule reb_10_2:
    input:
        "reb_10_2/Data/reb_10_2_data.csv",
        "../RE_Basics/Data/reb_10_2_data.csv",
        "reb_10_2/Results/reb_10_2_results.csv",
        "reb_10_2/Results/reb_10_2_parity.png",
        "reb_10_2/Results/reb_10_2_tau_residuals.png",
        "reb_10_2/Results/reb_10_2_yA_residuals.png",
        "../RE_Basics/Graphics/reb_10_2_parity.png",
        "../RE_Basics/Graphics/reb_10_2_tau_residuals.png",
        "../RE_Basics/Graphics/reb_10_2_yA_residuals.png"

rule reb_10_2_data:
    input: 
        "reb_10_2/Code/reb_10_2_cstr_data_generator.py"
    output:
        "reb_10_2/Data/reb_10_2_data.csv",
        "../RE_Basics/Data/reb_10_2_data.csv"
    shell:
        """
        python3 reb_10_2/Code/reb_10_2_cstr_data_generator.py
        """

rule reb_10_2_results:
    input:
        "reb_10_2/Code/reb_10_2_calculations.py",
        "reb_10_2/Data/reb_10_2_data.csv"
    output:
        "reb_10_2/Results/reb_10_2_results.csv",
        "reb_10_2/Results/reb_10_2_parity.png",
        "reb_10_2/Results/reb_10_2_tau_residuals.png",
        "reb_10_2/Results/reb_10_2_yA_residuals.png",
        "../RE_Basics/Graphics/reb_10_2_parity.png",
        "../RE_Basics/Graphics/reb_10_2_tau_residuals.png",
        "../RE_Basics/Graphics/reb_10_2_yA_residuals.png"
    shell:
        """
        python3 reb_10_2/Code/reb_10_2_calculations.py
        """