rule reb_19_5_3:
    input: 
        "reb_19_5_3/reb_19_5_3_data.csv",
        "reb_19_5_3/python/reb_19_5_3_results.csv",
        "reb_19_5_3/python/reb_19_5_3_parity.png",
        "reb_19_5_3/python/reb_19_5_3_PA0_residuals.png",
        "reb_19_5_3/python/reb_19_5_3_tf_residuals.png",
        "reb_19_5_3/matlab/reb_19_5_3_results.csv",
        "reb_19_5_3/matlab/reb_19_5_3_parity.png",
        "reb_19_5_3/matlab/reb_19_5_3_PA0_residuals.png",
        "reb_19_5_3/matlab/reb_19_5_3_tf_residuals.png",
        "../RE_Basics/examples/reb_19_5_3/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_3/equations.qmd",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_data.csv",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_results.csv",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_parity.png",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_PA0_residuals.png",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_tf_residuals.png",
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3.py",
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3.m",
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3_data.csv"

rule reb_19_5_3_python:
    input: 
        "reb_19_5_3/python/reb_19_5_3_bstr_data_generator.py",
        "reb_19_5_3/python/reb_19_5_3.py"
    output:
        "reb_19_5_3/reb_19_5_3_data.csv",
        "reb_19_5_3/python/reb_19_5_3_results.csv",
        "reb_19_5_3/python/reb_19_5_3_parity.png",
        "reb_19_5_3/python/reb_19_5_3_PA0_residuals.png",
        "reb_19_5_3/python/reb_19_5_3_tf_residuals.png"
    shell:
        """
        python3 reb_19_5_3/python/reb_19_5_3_bstr_data_generator.py
        python3 reb_19_5_3/python/reb_19_5_3.py
        """

rule reb_19_5_3_matlab:
    input:
        "reb_19_5_3/matlab/reb_19_5_3.m"
    output:
        "reb_19_5_3/matlab/reb_19_5_3_results.csv",
        "reb_19_5_3/matlab/reb_19_5_3_parity.png",
        "reb_19_5_3/matlab/reb_19_5_3_PA0_residuals.png",
        "reb_19_5_3/matlab/reb_19_5_3_tf_residuals.png"
    shell:
        """
         matlab -nodisplay -r "cd('reb_19_5_3/matlab');reb_19_5_3;exit"
        """

rule reb_19_5_3_re_basics:
    input:
        "reb_19_5_3/narrative.qmd",
        "reb_19_5_3/equations.qmd",
        "reb_19_5_3/python/reb_19_5_3_data.csv",
        "reb_19_5_3/python/reb_19_5_3_results.csv",
        "reb_19_5_3/python/reb_19_5_3_parity.png",
        "reb_19_5_3/python/reb_19_5_3_PA0_residuals.png",
        "reb_19_5_3/python/reb_19_5_3_tf_residuals.png"
    output:
        "../RE_Basics/examples/reb_19_5_3/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_3/equations.qmd",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_data.csv",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_results.csv",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_parity.png",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_PA0_residuals.png",
        "../RE_Basics/examples/reb_19_5_3/reb_19_5_3_tf_residuals.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_19_5_3
        mkdir ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/narrative.qmd ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/equations.qmd ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/reb_19_5_3_data.csv ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/python/reb_19_5_3_results.csv ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/python/reb_19_5_3_parity.png ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/python/reb_19_5_3_PA0_residuals.png ../RE_Basics/examples/reb_19_5_3
        cp reb_19_5_3/python/reb_19_5_3_tf_residuals.png ../RE_Basics/examples/reb_19_5_3
        """

rule reb_19_5_3_score:
    input:
        "reb_19_5_3/python/reb_19_5_3.py",
        "reb_19_5_3/reb_19_5_3_data.csv",
        "reb_19_5_3/matlab/reb_19_5_3.m"
    output:
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3.py",
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3_data.csv",
        "../SCoRE/reb_examples/reb_19_5_3/reb_19_5_3.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_19_5_3
        mkdir ../SCoRE/reb_examples/reb_19_5_3
        cp reb_19_5_3/python/reb_19_5_3.py ../SCoRE/reb_examples/reb_19_5_3
        cp reb_19_5_3/reb_19_5_3_data.csv ../SCoRE/reb_examples/reb_19_5_3
        cp reb_19_5_3/matlab/reb_19_5_3.m ../SCoRE/reb_examples/reb_19_5_3
        """
