rule reb_19_5_4:
    input: 
        "reb_19_5_4/reb_19_5_4_data.csv",
        "reb_19_5_4/python/reb_19_5_4_results.csv",
        "reb_19_5_4/python/reb_19_5_4_parity.png",
        "reb_19_5_4/python/reb_19_5_4_CS0_residuals.png",
        "reb_19_5_4/python/reb_19_5_4_tf_residuals.png",
        "reb_19_5_4/matlab/reb_19_5_4_results.csv",
        "reb_19_5_4/matlab/reb_19_5_4_parity.png",
        "reb_19_5_4/matlab/reb_19_5_4_CS0_residuals.png",
        "reb_19_5_4/matlab/reb_19_5_4_tf_residuals.png",
        "../RE_Basics/examples/reb_19_5_4/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_4/equations.qmd",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_data.csv",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_results.csv",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_parity.png",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_CS0_residuals.png",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_tf_residuals.png",
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4.py",
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4.m",
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4_data.csv"

rule reb_19_5_4_python:
    input: 
        "reb_19_5_4/python/reb_19_5_4_bstr_data_generator.py",
        "reb_19_5_4/python/reb_19_5_4.py"
    output:
        "reb_19_5_4/reb_19_5_4_data.csv",
        "reb_19_5_4/python/reb_19_5_4_results.csv",
        "reb_19_5_4/python/reb_19_5_4_parity.png",
        "reb_19_5_4/python/reb_19_5_4_CS0_residuals.png",
        "reb_19_5_4/python/reb_19_5_4_tf_residuals.png"
    shell:
        """
        python3 reb_19_5_4/python/reb_19_5_4_bstr_data_generator.py
        python3 reb_19_5_4/python/reb_19_5_4.py
        """

rule reb_19_5_4_matlab:
    input:
        "reb_19_5_4/matlab/reb_19_5_4.m",
        "reb_19_5_4/reb_19_5_4_data.csv"
    output:
        "reb_19_5_4/matlab/reb_19_5_4_results.csv",
        "reb_19_5_4/matlab/reb_19_5_4_parity.png",
        "reb_19_5_4/matlab/reb_19_5_4_CS0_residuals.png",
        "reb_19_5_4/matlab/reb_19_5_4_tf_residuals.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_19_5_4/matlab');reb_19_5_4;exit"
        """

rule reb_19_5_4_re_basics:
    input:
        "reb_19_5_4/narrative.qmd",
        "reb_19_5_4/equations.qmd",
        "reb_19_5_4/reb_19_5_4_data.csv",
        "reb_19_5_4/python/reb_19_5_4_results.csv",
        "reb_19_5_4/python/reb_19_5_4_parity.png",
        "reb_19_5_4/python/reb_19_5_4_CS0_residuals.png",
        "reb_19_5_4/python/reb_19_5_4_tf_residuals.png"
    output:
        "../RE_Basics/examples/reb_19_5_4/narrative.qmd",
        "../RE_Basics/examples/reb_19_5_4/equations.qmd",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_data.csv",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_results.csv",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_parity.png",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_CS0_residuals.png",
        "../RE_Basics/examples/reb_19_5_4/reb_19_5_4_tf_residuals.png"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_19_5_4
        mkdir ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/narrative.qmd ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/equations.qmd ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/reb_19_5_4_data.csv ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/python/reb_19_5_4_results.csv ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/python/reb_19_5_4_parity.png ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/python/reb_19_5_4_CS0_residuals.png ../RE_Basics/examples/reb_19_5_4
        cp reb_19_5_4/python/reb_19_5_4_tf_residuals.png ../RE_Basics/examples/reb_19_5_4
        """

rule reb_19_5_4_score:
    input:
        "reb_19_5_4/python/reb_19_5_4.py",
        "reb_19_5_4/matlab/reb_19_5_4.m",
        "reb_19_5_4/reb_19_5_4_data.csv"
    output:
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4.py",
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4.m",
        "../SCoRE/reb_examples/reb_19_5_4/reb_19_5_4_data.csv"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_19_5_4
        mkdir ../SCoRE/reb_examples/reb_19_5_4
        cp reb_19_5_4/python/reb_19_5_4.py ../SCoRE/reb_examples/reb_19_5_4
        cp reb_19_5_4/reb_19_5_4_data.csv ../SCoRE/reb_examples/reb_19_5_4
        cp reb_19_5_4/matlab/reb_19_5_4.m ../SCoRE/reb_examples/reb_19_5_4
        """
