rule reb_23_3_3:
    input:
        "../RE_Basics/examples/reb_23_3_3/narrative.qmd",
        "../RE_Basics/examples/reb_23_3_3/equations.qmd"

rule reb_23_3_3_data:
    input:
        
    output:
        
    shell:
        """
        
        """

rule reb_23_3_3_python:
    input:
        
    output:
        
    shell:
        """
        
        """

rule reb_23_3_3_matlab:
    input:
        
    output:
        
    shell:
        """
        matlab -nodisplay -r "cd('reb_23_3_3/matlab');reb_23_3_3;exit"
        """

rule reb_23_3_3_re_basics:
    input:
        "reb_23_3_3/narrative.qmd",
        "reb_23_3_3/equations.qmd"
    output:
        "../RE_Basics/examples/reb_23_3_3/narrative.qmd",
        "../RE_Basics/examples/reb_23_3_3/equations.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_23_3_3
        mkdir ../RE_Basics/examples/reb_23_3_3
        cp reb_23_3_3/narrative.qmd ../RE_Basics/examples/reb_23_3_3
        cp reb_23_3_3/equations.qmd ../RE_Basics/examples/reb_23_3_3
        """

rule reb_23_3_3_score:
    input:
        
    output:
        
    shell:
        """
        
        """