rule reb_J_7_1:
    input:
        "reb_J_7_1/matlab/results/reb_J_7_1_results.csv",
        "reb_J_7_1/python/results/reb_J_7_1_results.csv"

rule reb_J_7_1_python:
    input:
        "reb_J_7_1/python/code/reb_J_7_1_calculations.py"
    output:
        "reb_J_7_1/python/results/reb_J_7_1_results.csv"
    shell:
        """
        python reb_J_7_1/python/code/reb_J_7_1_calculations.py
        """

rule reb_J_7_1_matlab:
    input:
        "reb_J_7_1/matlab/code/reb_J_7_1_calculations.m"
    output:
        "reb_J_7_1/matlab/results/reb_J_7_1_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_7_1/matlab/code');\
        reb_J_7_1_calculations;exit"
        """