rule reb_J_7_3:
    input:
        "reb_J_7_3/matlab/results/reb_J_7_3_Tin_results.csv",
        "reb_J_7_3/matlab/results/reb_J_7_3_profile_results.csv",
        "reb_J_7_3/python/results/reb_J_7_3_Tin_results.csv",
        "reb_J_7_3/python/results/reb_J_7_3_profile_results.csv"

rule reb_J_7_3_python:
    input:
        "reb_J_7_3/python/code/reb_J_7_3.py"
    output:
        "reb_J_7_3/python/results/reb_J_7_3_Tin_results.csv",
        "reb_J_7_3/python/results/reb_J_7_3_profile_results.csv"
    shell:
        """
        python reb_J_7_3/python/code/reb_J_7_3.py
        """

rule reb_J_7_3_matlab:
    input:
        "reb_J_7_3/matlab/code/reb_J_7_3.m"
    output:
        "reb_J_7_3/matlab/results/reb_J_7_3_Tin_results.csv",
        "reb_J_7_3/matlab/results/reb_J_7_3_profile_results.csv"
    shell:
        """
        matlab -nodisplay -r "cd('reb_J_7_3/matlab/code');\
        reb_J_7_3;exit"
        """