rule reb_19_2:
    input:
        "reb_19_2/Data/reb_19_2_data_475.csv",
        "reb_19_2/Data/reb_19_2_data_500.csv",
        "reb_19_2/Data/reb_19_2_data_525.csv",
        "reb_19_2/Data/reb_19_2_data_filenames.csv",
        "reb_19_2/Data/reb_19_2_data.csv",
        "../RE_Basics/Data/reb_19_2_data.csv",
        "reb_19_2/Results/reb_19_2_Arrhenius_lin.csv",
        "reb_19_2/Results/reb_19_2_Arrhenius_lin.png",
        "reb_19_2/Results/reb_19_2_Arrhenius_resp_fcn.csv",
        "reb_19_2/Results/reb_19_2_Arrhenius_resp_fcn.png",
        "reb_19_2/Results/reb_19_2_lin_params.csv",
        "reb_19_2/Results/reb_19_2_model_475.png",
        "reb_19_2/Results/reb_19_2_model_500.png",
        "reb_19_2/Results/reb_19_2_model_525.png",
        "reb_19_2/Results/reb_19_2_parity_475.png",
        "reb_19_2/Results/reb_19_2_parity_500.png",
        "reb_19_2/Results/reb_19_2_parity_525.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_475.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_500.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_525.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_475.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_500.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_525.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_475.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_500.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_525.png",
        "reb_19_2/Results/reb_19_2_resp_fcn_params.csv",
        "../RE_Basics/Graphics/reb_19_2_Arrhenius_lin.png",
        "../RE_Basics/Graphics/reb_19_2_Arrhenius_resp_fcn.png",
        "../RE_Basics/Graphics/reb_19_2_model_475.png",
        "../RE_Basics/Graphics/reb_19_2_model_500.png",
        "../RE_Basics/Graphics/reb_19_2_model_525.png",
        "../RE_Basics/Graphics/reb_19_2_parity_475.png",
        "../RE_Basics/Graphics/reb_19_2_parity_500.png",
        "../RE_Basics/Graphics/reb_19_2_parity_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_525.png"

rule reb_19_2_data:
    input: "reb_19_2/Code/reb_19_2_bstr_data_generator.py"
    output:
        "reb_19_2/Data/reb_19_2_data.csv",
        "../RE_Basics/Data/reb_19_2_data.csv"
    shell:
        """
        python reb_19_2/Code/reb_19_2_bstr_data_generator.py
        """

rule reb_19_2_data_blocks:
    input: 
        "reb_19_2/Code/reb_19_2_create_data_blocks.py",
        "reb_19_2/Data/reb_19_2_data.csv"
    output:
        "reb_19_2/Data/reb_19_2_data_475.csv",
        "reb_19_2/Data/reb_19_2_data_500.csv",
        "reb_19_2/Data/reb_19_2_data_525.csv",
        "reb_19_2/Data/reb_19_2_data_filenames.csv"
    shell:
        """
        python reb_19_2/Code/reb_19_2_create_data_blocks.py
        """

rule reb_19_2_results_resp:
    input:
        "reb_19_2/Code/reb_19_2_calcs_resp_fcn.py",
        "reb_19_2/Code/reb_19_2_response_fcn.py",
        "reb_19_2/Data/reb_19_2_data_475.csv",
        "reb_19_2/Data/reb_19_2_data_500.csv",
        "reb_19_2/Data/reb_19_2_data_525.csv",
        "reb_19_2/Data/reb_19_2_data_filenames.csv"
    output:
        "reb_19_2/Results/reb_19_2_parity_475.png",
        "reb_19_2/Results/reb_19_2_parity_500.png",
        "reb_19_2/Results/reb_19_2_parity_525.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_475.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_500.png",
        "reb_19_2/Results/reb_19_2_residual_PA0_525.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_475.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_500.png",
        "reb_19_2/Results/reb_19_2_residual_PB0_525.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_475.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_500.png",
        "reb_19_2/Results/reb_19_2_residual_t_rxn_525.png",
        "reb_19_2/Results/reb_19_2_resp_fcn_params.csv",
        "../RE_Basics/Graphics/reb_19_2_parity_475.png",
        "../RE_Basics/Graphics/reb_19_2_parity_500.png",
        "../RE_Basics/Graphics/reb_19_2_parity_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PA0_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_PB0_525.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_475.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_500.png",
        "../RE_Basics/Graphics/reb_19_2_residual_t_rxn_525.png"
    shell:
        """
        python reb_19_2/Code/reb_19_2_calcs_resp_fcn.py
        """

rule reb_19_2_results_lin:
    input:
        "reb_19_2/Code/reb_19_2_calcs_lin_fcn.py",
        "reb_19_2/Data/reb_19_2_data_475.csv",
        "reb_19_2/Data/reb_19_2_data_500.csv",
        "reb_19_2/Data/reb_19_2_data_525.csv",
        "reb_19_2/Data/reb_19_2_data_filenames.csv"
    output:
        "reb_19_2/Results/reb_19_2_model_475.png",
        "reb_19_2/Results/reb_19_2_model_500.png",
        "reb_19_2/Results/reb_19_2_model_525.png",
        "reb_19_2/Results/reb_19_2_lin_params.csv",
        "../RE_Basics/Graphics/reb_19_2_model_475.png",
        "../RE_Basics/Graphics/reb_19_2_model_500.png",
        "../RE_Basics/Graphics/reb_19_2_model_525.png"
    shell:
        """
        python reb_19_2/Code/reb_19_2_calcs_lin_fcn.py
        """

rule reb_19_2_Arrhenius_lin:
    input:
        "reb_19_2/Code/reb_19_2_Arrhenius_lin.py",
        "reb_19_2/Results/reb_19_2_lin_params.csv"
    output:
        "reb_19_2/Results/reb_19_2_Arrhenius_lin.csv",
        "reb_19_2/Results/reb_19_2_Arrhenius_lin.png",
        "../RE_Basics/Graphics/reb_19_2_Arrhenius_lin.png"
    shell:
        """
        python reb_19_2/Code/reb_19_2_Arrhenius_lin.py
        """

rule reb_19_2_Arrhenius_resp:
    input:
        "reb_19_2/Code/reb_19_2_Arrhenius_resp_fcn.py",
        "reb_19_2/Results/reb_19_2_resp_fcn_params.csv"
    output:
        "reb_19_2/Results/reb_19_2_Arrhenius_resp_fcn.csv",
        "reb_19_2/Results/reb_19_2_Arrhenius_resp_fcn.png",
        "../RE_Basics/Graphics/reb_19_2_Arrhenius_resp_fcn.png"
    shell:
        """
        python reb_19_2/Code/reb_19_2_Arrhenius_resp_fcn.py
        """