rule reb_10_5_3:
    input:
        "reb_10_5_3/matlab/results.csv",
        "reb_10_5_3/matlab/concentration_profile.png",
        "reb_10_5_3/matlab/temperature_profile.png",
        "reb_10_5_3/python/results.csv",
        "reb_10_5_3/python/concentration_profile.png",
        "reb_10_5_3/python/temperature_profile.png",
        "../RE_Basics/examples/reb_10_5_3/concentration_profile.png",
        "../RE_Basics/examples/reb_10_5_3/temperature_profile.png",
        "../RE_Basics/examples/reb_10_5_3/results.csv",
        "../RE_Basics/examples/reb_10_5_3/narrative.qmd",
        "../RE_Basics/examples/reb_10_5_3/equations.qmd",
        "../SCoRE/reb_examples/reb_10_5_3/reb_10_5_3.py",
        "../SCoRE/reb_examples/reb_10_5_3/reb_10_5_3.m"

rule reb_10_5_3_python:
    input:
        "reb_10_5_3/python/reb_10_5_3.py"
    output:
        "reb_10_5_3/python/results.csv",
        "reb_10_5_3/python/concentration_profile.png",
        "reb_10_5_3/python/temperature_profile.png"
    shell:
        """
        python3 reb_10_5_3/python/reb_10_5_3.py
        """

rule reb_10_5_3_matlab:
    input:
        "reb_10_5_3/matlab/reb_10_5_3.m"
    output:
        "reb_10_5_3/matlab/results.csv",
        "reb_10_5_3/matlab/concentration_profile.png",
        "reb_10_5_3/matlab/temperature_profile.png"
    shell:
        """
        matlab -nodisplay -r "cd('reb_10_5_3/matlab');reb_10_5_3;exit"
        """

rule reb_10_5_3_re_basics:
    input:
        "reb_10_5_3/python/concentration_profile.png",
        "reb_10_5_3/python/temperature_profile.png",
        "reb_10_5_3/python/results.csv",
        "reb_10_5_3/narrative.qmd",
        "reb_10_5_3/equations.qmd"
    output:
        "../RE_Basics/examples/reb_10_5_3/concentration_profile.png",
        "../RE_Basics/examples/reb_10_5_3/temperature_profile.png",
        "../RE_Basics/examples/reb_10_5_3/results.csv",
        "../RE_Basics/examples/reb_10_5_3/narrative.qmd",
        "../RE_Basics/examples/reb_10_5_3/equations.qmd"
    shell:
        """
        rm -rf ../RE_Basics/examples/reb_10_5_3
        mkdir ../RE_Basics/examples/reb_10_5_3
        cp reb_10_5_3/python/concentration_profile.png ../RE_Basics/examples/reb_10_5_3
        cp reb_10_5_3/python/temperature_profile.png ../RE_Basics/examples/reb_10_5_3
        cp reb_10_5_3/python/results.csv ../RE_Basics/examples/reb_10_5_3
        cp reb_10_5_3/narrative.qmd ../RE_Basics/examples/reb_10_5_3
        cp reb_10_5_3/equations.qmd ../RE_Basics/examples/reb_10_5_3
        """

rule reb_10_5_3_score:
    input:
        "reb_10_5_3/python/reb_10_5_3.py",
        "reb_10_5_3/matlab/reb_10_5_3.m"
    output:
        "../SCoRE/reb_examples/reb_10_5_3/reb_10_5_3.py",
        "../SCoRE/reb_examples/reb_10_5_3/reb_10_5_3.m"
    shell:
        """
        rm -rf ../SCoRE/reb_examples/reb_10_5_3
        mkdir ../SCoRE/reb_examples/reb_10_5_3
        cp reb_10_5_3/python/reb_10_5_3.py ../SCoRE/reb_examples/reb_10_5_3
        cp reb_10_5_3/matlab/reb_10_5_3.m ../SCoRE/reb_examples/reb_10_5_3
        """
